<?php
namespace App\Services;
use App\Models\{Invoice,InvoiceItem,Customer,Order}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class InvoiceService {
 public function generateInvoiceNumber():string { $year=now()->year; $last=Invoice::withTrashed()->where('invoice_number','like',"INV-{$year}-%")->lockForUpdate()->orderByDesc('id')->value('invoice_number'); $n=$last?(int)substr($last,strrpos($last,'-')+1)+1:1; return sprintf('INV-%d-%06d',$year,$n); }
 public function snapshotCustomer(Customer $c):array{return ['billing_name'=>$c->business_name,'billing_contact_name'=>$c->contact_name??null,'billing_address'=>$c->address??null,'billing_city'=>$c->city??null,'billing_state'=>$c->state??null,'billing_pincode'=>$c->pincode??null,'billing_gstin'=>$c->gstin??null,'billing_mobile'=>$c->mobile??null,'billing_email'=>$c->email??null];}
 public function calculateTotals(array $items,array $data):array{$subtotal=0;$discount=0;$tax=0;$normalized=[];foreach(array_values($items) as $idx=>$row){$qty=(float)$row['quantity'];$price=(float)$row['unit_price'];$line=$qty*$price;$d=(float)($row['discount']??0);$dtype=$row['discount_type']??'fixed';$d=$dtype==='percentage'?min($line,$line*$d/100):min($line,$d);$taxable=$line-$d;$tr=(float)($row['tax_rate']??0);$ta=$taxable*$tr/100;$total=$taxable+$ta;$subtotal+=$line;$discount+=$d;$tax+=$ta;$normalized[]=[$row,$taxable,$ta,$total,$d,$idx];}$taxable=$subtotal-$discount;$grand=$taxable+$tax+(float)($data['shipping_amount']??0)+(float)($data['other_charges']??0)+(float)($data['round_off']??0);return compact('subtotal','discount','taxable','tax','grand','normalized');}
 public function createInvoice(array $data,?int $userId=null):Invoice {return DB::transaction(function()use($data,$userId){$c=Customer::findOrFail($data['customer_id']);$t=$this->calculateTotals($data['items'],$data);$i=Invoice::create(array_merge(['invoice_number'=>$this->generateInvoiceNumber(),'customer_id'=>$c->id,'order_id'=>$data['order_id']??null,'invoice_date'=>$data['invoice_date'],'due_date'=>$data['due_date']??null,'status'=>'draft','payment_status'=>'unpaid','subtotal'=>$t['subtotal'],'discount'=>$t['discount'],'taxable_amount'=>$t['taxable'],'tax_amount'=>$t['tax'],'shipping_amount'=>$data['shipping_amount']??0,'other_charges'=>$data['other_charges']??0,'round_off'=>$data['round_off']??0,'grand_total'=>$t['grand'],'paid_amount'=>0,'outstanding_amount'=>$t['grand'],'notes'=>$data['notes']??null,'terms'=>$data['terms']??null,'created_by'=>$userId],$this->snapshotCustomer($c)));foreach($t['normalized'] as [$r,$taxable,$ta,$total,$d,$idx])$i->items()->create(['product_id'=>$r['product_id']??null,'order_item_id'=>$r['order_item_id']??null,'description'=>$r['description'],'quantity'=>$r['quantity'],'unit'=>$r['unit']??'pcs','unit_price'=>$r['unit_price'],'discount'=>$d,'discount_type'=>$r['discount_type']??'fixed','taxable_amount'=>$taxable,'tax_rate'=>$r['tax_rate']??0,'tax_amount'=>$ta,'total'=>$total,'sort_order'=>$idx]);return $i->load('items','customer','order');});}
 public function updateInvoice(Invoice $i,array $data,?int $userId=null):Invoice {if($i->status!=='draft')throw ValidationException::withMessages(['invoice'=>'Only draft invoices can be edited.']);return DB::transaction(function()use($i,$data,$userId){$t=$this->calculateTotals($data['items'],$data);$i->update(array_merge(['order_id'=>$data['order_id']??null,'invoice_date'=>$data['invoice_date'],'due_date'=>$data['due_date']??null,'subtotal'=>$t['subtotal'],'discount'=>$t['discount'],'taxable_amount'=>$t['taxable'],'tax_amount'=>$t['tax'],'shipping_amount'=>$data['shipping_amount']??0,'other_charges'=>$data['other_charges']??0,'round_off'=>$data['round_off']??0,'grand_total'=>$t['grand'],'outstanding_amount'=>$t['grand']-$i->paid_amount,'notes'=>$data['notes']??null,'terms'=>$data['terms']??null,'updated_by'=>$userId]));$i->items()->delete();foreach($t['normalized'] as [$r,$taxable,$ta,$total,$d,$idx])$i->items()->create(['product_id'=>$r['product_id']??null,'order_item_id'=>$r['order_item_id']??null,'description'=>$r['description'],'quantity'=>$r['quantity'],'unit'=>$r['unit']??'pcs','unit_price'=>$r['unit_price'],'discount'=>$d,'discount_type'=>$r['discount_type']??'fixed','taxable_amount'=>$taxable,'tax_rate'=>$r['tax_rate']??0,'tax_amount'=>$ta,'total'=>$total,'sort_order'=>$idx]);return $i->fresh('items','customer','order');});}
 public function syncPaymentStatus(Invoice $i):Invoice {$paid=(float)$i->paymentAllocations()->whereNull('reversed_at')->whereHas('payment',fn($q)=>$q->where('status','completed')->where('direction','received'))->sum('allocated_amount');$out=max(0,(float)$i->grand_total-$paid);$status=$paid<=0?'unpaid':($paid<(float)$i->grand_total?'partially_paid':($paid>(float)$i->grand_total?'overpaid':'paid'));$i->update(['paid_amount'=>$paid,'outstanding_amount'=>$out,'payment_status'=>$status]);return $i;}
 public function issue(Invoice $i):Invoice{if($i->status!=='draft')throw ValidationException::withMessages(['invoice'=>'Only draft invoices can be issued.']);$i->update(['status'=>'issued']);return $i;} public function sendInvoice(Invoice $i):Invoice{if(in_array($i->status,['draft','cancelled'],true))throw ValidationException::withMessages(['invoice'=>'Only issued invoices can be sent.']);$i->update(['status'=>'sent']);return $i;} public function createFromOrder(Order $order,?int $userId=null):Invoice{if(method_exists($order,'invoices') && $order->invoices()->where('status','!=','cancelled')->exists())throw ValidationException::withMessages(['order'=>'An active invoice already exists for this order.']);$order->loadMissing(['customer','items.product']);$items=$order->items->map(fn($x)=>['product_id'=>$x->product_id,'order_item_id'=>$x->id,'description'=>$x->description??($x->product->name??'Item'),'quantity'=>$x->quantity,'unit'=>'pcs','unit_price'=>$x->unit_price??$x->price??0,'discount'=>0,'discount_type'=>'fixed','tax_rate'=>0])->values()->all();return $this->createInvoice(['customer_id'=>$order->customer_id,'order_id'=>$order->id,'invoice_date'=>today()->format('Y-m-d'),'due_date'=>null,'items'=>$items,'shipping_amount'=>0,'other_charges'=>0,'round_off'=>0,'notes'=>null,'terms'=>null],$userId);}
 public function cancel(Invoice $i,string $reason,?int $uid=null):Invoice{if((float)$i->paid_amount>0)throw ValidationException::withMessages(['invoice'=>'Invoice with payments cannot be cancelled until financial reversal is handled.']);$i->update(['status'=>'cancelled','cancelled_by'=>$uid,'cancelled_at'=>now(),'cancellation_reason'=>$reason]);return $i;}
 public function duplicate(Invoice $i,?int $uid=null):Invoice{$i->load('items');return DB::transaction(function()use($i,$uid){$n=$i->replicate();$n->invoice_number=$this->generateInvoiceNumber();$n->status='draft';$n->payment_status='unpaid';$n->paid_amount=0;$n->outstanding_amount=0;$n->created_by=$uid;$n->cancelled_by=null;$n->cancelled_at=null;$n->cancellation_reason=null;$n->save();foreach($i->items as $x){$r=$x->replicate();$r->invoice_id=$n->id;$r->save();}return $n->load('items','customer','order');});}
}
