<?php
namespace App\Services;
use App\Models\Payment; use App\Models\PaymentAllocation; use Illuminate\Support\Facades\DB; use Illuminate\Database\Eloquent\Builder; use Carbon\Carbon; use RuntimeException;
class PaymentService {
 public function generatePaymentNumber():string { return DB::transaction(function(){ $y=now()->year; $last=Payment::withTrashed()->where('payment_number','like',"PAY-$y-%")->lockForUpdate()->orderByDesc('id')->value('payment_number'); $n=$last ? ((int)substr($last,-6))+1 : 1; return sprintf('PAY-%d-%06d',$y,$n); }); }
 public function generateReceiptNumber():string { return 'RCP-'.now()->format('Ym').'-'.str_pad((string)(Payment::whereNotNull('receipt_number')->count()+1),6,'0',STR_PAD_LEFT); }
 public function createPayment(array $data, ?int $userId=null):Payment { return DB::transaction(function()use($data,$userId){ $data['payment_number']=$this->generatePaymentNumber(); $data['status']=$data['status']??'completed'; $data['created_by']=$userId; if($data['direction']==='received')$data['received_by']=$userId; else $data['paid_by']=$userId; $data['receipt_number']=$this->generateReceiptNumber(); $alloc=$data['allocations']??[]; unset($data['allocations']); $p=Payment::create($data); if($alloc)$this->allocatePayment($p,$alloc,$userId); return $p->fresh(['allocations']); }); }
 public function calculateUnallocated(Payment $p):float { return max(0,(float)$p->amount-(float)$p->allocations()->whereNull('reversed_at')->sum('allocated_amount')); }
 public function allocatePayment(Payment $p,array $rows,?int $userId=null):void { DB::transaction(function()use($p,$rows,$userId){ $p=Payment::whereKey($p->id)->lockForUpdate()->firstOrFail(); if($p->status!=='completed')throw new RuntimeException('Only completed payments can be allocated.'); $remaining=$this->calculateUnallocated($p); foreach($rows as $r){$amt=(float)($r['amount']??0); if($amt<=0)continue; if($amt>$remaining+0.0001)throw new RuntimeException('Allocation exceeds payment unallocated amount.'); $targets=array_filter([$r['invoice_id']??null,$r['order_id']??null,$r['purchase_id']??null]); if(count($targets)!==1)throw new RuntimeException('Each allocation must target exactly one document.'); $existing=$this->documentAllocated($r); $total=$this->documentTotal($r); if($total!==null && $existing+$amt>$total+0.0001)throw new RuntimeException('Allocation exceeds document outstanding amount.'); PaymentAllocation::create(['payment_id'=>$p->id,'invoice_id'=>$r['invoice_id']??null,'order_id'=>$r['order_id']??null,'purchase_id'=>$r['purchase_id']??null,'allocated_amount'=>$amt,'allocation_date'=>now()->toDateString(),'notes'=>$r['notes']??null]); $remaining-=$amt; } }); }
 protected function documentTotal(array $r):?float { foreach(['invoice_id'=>'Invoice','order_id'=>'Order','purchase_id'=>'Purchase'] as $key=>$class){ if(!empty($r[$key])){ $model="App\\Models\\$class"; if(!class_exists($model))return null; $m=$model::find($r[$key]); if(!$m)return null; foreach(['grand_total','total','total_amount','net_total'] as $f)if(isset($m->{$f}))return (float)$m->{$f}; }} return null; }
 protected function documentAllocated(array $r):float { $q=PaymentAllocation::whereNull('reversed_at'); foreach(['invoice_id','order_id','purchase_id'] as $k)if(!empty($r[$k]))$q->where($k,$r[$k]); return (float)$q->sum('allocated_amount'); }
 public function removeAllocation(PaymentAllocation $a,?int $userId=null,string $reason='Manual reversal'):void { DB::transaction(function()use($a,$userId,$reason){$a=PaymentAllocation::lockForUpdate()->findOrFail($a->id); if($a->reversed_at)throw new RuntimeException('Allocation already reversed.'); $a->update(['reversed_at'=>now(),'reversed_by'=>$userId,'reversal_reason'=>$reason]);}); }
 public function refundPayment(Payment $p,array $data,?int $userId=null):Payment { return DB::transaction(function()use($p,$data,$userId){$p=Payment::lockForUpdate()->findOrFail($p->id); $ref=(float)$p->refunds()->whereIn('status',['completed','partially_refunded'])->sum('amount'); $amt=(float)$data['amount']; if($ref+$amt>(float)$p->amount+0.0001)throw new RuntimeException('Refund exceeds refundable amount.'); $data['direction']=$p->direction==='received'?'paid':'received'; $data['payment_type']='refund'; $data['customer_id']=$p->customer_id; $data['supplier_id']=$p->supplier_id; $data['order_id']=$p->order_id; $data['purchase_id']=$p->purchase_id; $data['invoice_id']=$p->invoice_id; $data['refund_of_payment_id']=$p->id; $data['status']='completed'; $data['created_by']=$userId; $data['payment_number']=$this->generatePaymentNumber(); $data['receipt_number']=$this->generateReceiptNumber(); $data['received_by']=$data['direction']==='received'?$userId:null; $data['paid_by']=$data['direction']==='paid'?$userId:null; return tap(Payment::create($data),function()use($p,$ref,$amt){$new=$ref+$amt; $p->update(['status'=>$new >= (float)$p->amount ? 'refunded':'partially_refunded']);}); }); }
 public function cancelPayment(Payment $p,?int $userId=null):void { DB::transaction(function()use($p,$userId){$p=Payment::lockForUpdate()->findOrFail($p->id); if($p->status==='refunded')throw new RuntimeException('Refunded payment cannot be cancelled.'); $p->allocations()->whereNull('reversed_at')->update(['reversed_at'=>now(),'reversed_by'=>$userId,'reversal_reason'=>'Payment cancelled']); $p->update(['status'=>'cancelled']);}); }
 public function approvePayment(Payment $p,?int $userId=null):void{$p->update(['status'=>'completed','approved_by'=>$userId,'approved_at'=>now()]);}
 public function getCustomerLedger(int $customerId,?string $from=null,?string $to=null){$rows=[]; $p=Payment::where('customer_id',$customerId)->where('status','completed')->when($from,fn($q)=>$q->whereDate('payment_date','>=',$from))->when($to,fn($q)=>$q->whereDate('payment_date','<=',$to))->orderBy('payment_date')->orderBy('id')->get(); foreach($p as $x)$rows[]=['date'=>$x->payment_date,'reference'=>$x->payment_number,'type'=>$x->payment_type,'debit'=>$x->direction==='paid'?(float)$x->amount:0,'credit'=>$x->direction==='received'?(float)$x->amount:0]; return collect($rows);}
 public function getSupplierLedger(int $supplierId,?string $from=null,?string $to=null){$rows=[]; $p=Payment::where('supplier_id',$supplierId)->where('status','completed')->when($from,fn($q)=>$q->whereDate('payment_date','>=',$from))->when($to,fn($q)=>$q->whereDate('payment_date','<=',$to))->orderBy('payment_date')->orderBy('id')->get(); foreach($p as $x)$rows[]=['date'=>$x->payment_date,'reference'=>$x->payment_number,'type'=>$x->payment_type,'debit'=>$x->direction==='paid'?(float)$x->amount:0,'credit'=>$x->direction==='received'?(float)$x->amount:0]; return collect($rows);}
 public function query(array $filters=[]):Builder
 {
  $q=Payment::query()->with(['customer','supplier','order','purchase','creator','allocations']);
  $q->when($filters['search']??null,function($q,$s){
   $q->where(function($q)use($s){
    $q->where('payment_number','like',"%$s%")
      ->orWhere('reference_number','like',"%$s%")
      ->orWhereHas('customer',fn($q)=>$q->where('business_name','like',"%$s%"))
      ->orWhereHas('supplier',fn($q)=>$q->where('business_name','like',"%$s%"));
   });
  });
  foreach(['direction','status','method','payment_type'] as $f) $q->when($filters[$f]??null,fn($q,$v)=>$q->where($f,$v));
  $q->when($filters['from']??null,fn($q,$v)=>$q->whereDate('payment_date','>=',$v));
  $q->when($filters['to']??null,fn($q,$v)=>$q->whereDate('payment_date','<=',$v));
  return $q->latest('id');
 }
}
