@extends('layouts.admin')
@push('styles')<link rel="stylesheet" href="{{ asset('css/staff-attendance.css') }}">@endpush
@push('scripts')<script src="{{ asset('js/staff-attendance.js') }}"></script>@endpush
@section('content')
<div class="hr-head"><div><div class="hr-kicker">HR MANAGEMENT</div><h1>Staff Attendance</h1><p>Mark daily attendance and monitor workforce presence.</p></div></div>
@if(session('success'))<div class="hr-alert">{{ session('success') }}</div>@endif
<div class="hr-stats"><div><span>Present</span><strong>{{ $summary['present'] }}</strong></div><div><span>Late</span><strong>{{ $summary['late'] }}</strong></div><div><span>Absent</span><strong>{{ $summary['absent'] }}</strong></div><div><span>Leave</span><strong>{{ $summary['leave'] }}</strong></div><div><span>Half Day</span><strong>{{ $summary['half_day'] }}</strong></div></div>
<form class="hr-filter" method="GET"><label>Date<input type="date" name="date" value="{{ $date }}"></label><button class="hr-btn hr-btn-primary">Load</button></form>
<div class="hr-card"><div class="hr-card-head"><div><h3>Daily Attendance</h3><p>{{ \Carbon\Carbon::parse($date)->format('d M Y') }}</p></div><button form="bulk-attendance" class="hr-btn hr-btn-primary">Save All</button></div>
<form id="bulk-attendance" method="POST" action="{{ route('admin.attendance.bulk') }}">@csrf<input type="hidden" name="attendance_date" value="{{ $date }}"><div class="hr-table-wrap"><table class="hr-table attendance-table"><thead><tr><th>Employee</th><th>Status</th><th>Check In</th><th>Check Out</th><th>Remarks</th><th></th></tr></thead><tbody>@forelse($staff as $person)@php($a=$records->get($person->id))<tr><td><strong>{{ $person->full_name }}</strong><small>{{ $person->employee_code }} · {{ $person->department ?: '—' }}</small></td><td><select name="rows[{{ $person->id }}][status]">@foreach(['present','absent','late','half_day','leave','holiday'] as $s)<option value="{{ $s }}" @selected(($a->status ?? 'present')===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select></td><td><input type="time" name="rows[{{ $person->id }}][check_in]" value="{{ $a?->check_in }}"></td><td><input type="time" name="rows[{{ $person->id }}][check_out]" value="{{ $a?->check_out }}"></td><td><input name="rows[{{ $person->id }}][remarks]" value="{{ $a?->remarks }}"></td><td>@if($a)<a href="{{ route('admin.attendance.edit',$a) }}">Edit</a>@endif</td></tr>@empty<tr><td colspan="6" class="hr-empty">No active staff found.</td></tr>@endforelse</tbody></table></div></form></div>
@endsection
