@extends('layouts.admin')
@push('styles')<link rel="stylesheet" href="{{ asset('css/staff-attendance.css') }}">@endpush
@section('content')
<div class="hr-head"><div><div class="hr-kicker">HR MANAGEMENT</div><h1>Prepare Salary</h1><p>Select an employee and month. Attendance is calculated automatically.</p></div></div>
@if($errors->any())<div class="hr-alert hr-error">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('admin.salary.store') }}" class="hr-card">
@csrf @method('POST')
<div class="hr-form-grid"><div class="hr-section"><h3>Salary Period</h3><div class="hr-fields"><label>Staff *<select name="staff_id" required>@foreach($staff as $person)<option value="{{ $person->id }}" @selected(old('staff_id',request('staff_id'))==$person->id)>{{ $person->full_name }} — {{ $person->employee_code }} — ₹{{ number_format($person->salary ?? 0,2) }}</option>@endforeach</select></label><label>Month *<input type="month" name="salary_period" value="{{ old('salary_period',now()->format('Y-m')) }}" required></label></div></div><div class="hr-section"><h3>Adjustments</h3><div class="hr-fields"><label>Paid Leave Days<input type="number" step="0.5" min="0" name="paid_leave_days" value="{{ old('paid_leave_days',0) }}"></label><label>Payable Days Override <small>Leave blank for automatic calculation</small><input type="number" step="0.5" min="0" name="payable_days" value="{{ old('payable_days') }}"></label><label>Bonus<input type="number" step="0.01" min="0" name="bonus" value="{{ old('bonus',0) }}"></label><label>Deduction<input type="number" step="0.01" min="0" name="deduction" value="{{ old('deduction',0) }}"></label></div></div><div class="hr-section"><h3>Payment</h3><div class="hr-fields"><label>Payment Date<input type="date" name="payment_date" value="{{ old('payment_date',now()->toDateString()) }}"></label><label>Payment Method<select name="payment_method"><option value="">Select later</option>@foreach(['cash','upi','bank_transfer','cheque','neft','rtgs','imps','other'] as $m)<option value="{{ $m }}">{{ ucwords(str_replace('_',' ',$m)) }}</option>@endforeach</select></label><label>Reference<input name="reference_number" value="{{ old('reference_number') }}"></label></div></div><div class="hr-section"><h3>Notes</h3><textarea class="hr-full" name="notes" rows="4">{{ old('notes') }}</textarea></div></div><div class="hr-form-footer"><a class="hr-btn" href="{{ route('admin.salary.index') }}">Cancel</a><button class="hr-btn hr-btn-primary">Calculate & Prepare</button></div></form>
@endsection
