@extends('layouts.admin')
@push('styles')<link rel="stylesheet" href="{{ asset('css/staff-attendance.css') }}">@endpush
@section('content')
<div class="hr-head"><div><div class="hr-kicker">HR MANAGEMENT</div><h1>Salary Payments</h1><p>Calculate monthly salary from attendance, apply bonus/deductions and mark payment.</p></div><a class="hr-btn hr-btn-primary" href="{{ route('admin.salary.create') }}">+ Prepare Salary</a></div>
@if(session('success'))<div class="hr-alert">{{ session('success') }}</div>@endif
<div class="hr-stats"><div><span>Active Staff</span><strong>{{ $stats['staff'] }}</strong></div><div><span>Salary Records</span><strong>{{ $stats['count'] }}</strong></div><div><span>Draft</span><strong>{{ $stats['draft'] }}</strong></div><div><span>Paid This Month</span><strong>₹{{ number_format($stats['paid'],2) }}</strong></div></div>
<form class="hr-filter" method="GET"><input name="q" value="{{ request('q') }}" placeholder="Search employee / code..."><select name="month">@for($m=1;$m<=12;$m++)<option value="{{ $m }}" @selected($month===$m)>{{ \Carbon\Carbon::create()->month($m)->format('F') }}</option>@endfor</select><select name="year">@for($y=now()->year-2;$y<=now()->year+1;$y++)<option value="{{ $y }}" @selected($year===$y)>{{ $y }}</option>@endfor</select><button class="hr-btn">Load</button></form>
<div class="hr-card"><div class="hr-table-wrap"><table class="hr-table"><thead><tr><th>Employee</th><th>Base Salary</th><th>Payable Days</th><th>Earned</th><th>Bonus</th><th>Deduction</th><th>Net</th><th>Status</th><th></th></tr></thead><tbody>@forelse($payments as $salary)<tr><td><strong>{{ $salary->staff->full_name }}</strong><small>{{ $salary->staff->employee_code }}</small></td><td>₹{{ number_format($salary->base_salary,2) }}</td><td>{{ number_format($salary->payable_days,2) }} / {{ number_format($salary->working_days,0) }}</td><td>₹{{ number_format($salary->attendance_earned,2) }}</td><td>₹{{ number_format($salary->bonus,2) }}</td><td>₹{{ number_format($salary->deduction,2) }}</td><td><strong>₹{{ number_format($salary->net_salary,2) }}</strong></td><td><span class="hr-badge hr-{{ $salary->status === 'paid' ? 'active' : ($salary->status === 'cancelled' ? 'absent' : 'half_day') }}">{{ ucfirst($salary->status) }}</span></td><td class="hr-actions"><a href="{{ route('admin.salary.show',$salary) }}">View</a>@if($salary->status!=='paid')<a href="{{ route('admin.salary.edit',$salary) }}">Edit</a>@endif</td></tr>@empty<tr><td colspan="9" class="hr-empty">No salary records for this month. Click “Prepare Salary” to create one.</td></tr>@endforelse</tbody></table></div><div class="hr-pagination">{{ $payments->links() }}</div></div>
@endsection
