@extends('layouts.admin')
@section('title','Quotations — JALVAN ERP')
@section('page_title','Quotations')
@section('breadcrumb','Sales / Quotations')
@push('styles')<link rel="stylesheet" href="{{ asset('css/quotation.css') }}">@endpush
@push('scripts')<script src="{{ asset('js/quotation.js') }}" defer></script>@endpush
@section('content')
<div class="qt-page"><div class="qt-hero"><div><span class="qt-kicker">SALES PROPOSALS</span><h1>Quotations</h1><p>Manage proposals, pricing and customer approvals.</p></div><a class="qt-btn qt-btn-primary" href="{{ route('admin.quotations.create') }}">+ New Quotation</a></div>
<div class="qt-stats"><div><span>Total</span><strong>{{ $stats['total'] }}</strong><small>All quotations</small></div><div><span>Drafts</span><strong>{{ $stats['draft'] }}</strong><small>Still editable</small></div><div><span>Pending</span><strong>{{ $stats['pending'] }}</strong><small>Awaiting approval</small></div><div><span>Approved</span><strong>{{ $stats['approved'] }}</strong><small>Ready for conversion</small></div><div><span>Converted</span><strong>{{ $stats['converted'] }}</strong><small>Moved to orders</small></div><div><span>Total Value</span><strong>₹{{ number_format($stats['value'],2) }}</strong><small>Quotation pipeline</small></div></div>
<form class="qt-filters" method="GET"><input name="q" value="{{ request('q') }}" placeholder="Search quotation, customer, mobile..."><select name="status"><option value="">All Status</option>@foreach(['draft','sent','viewed','approved','rejected','expired','converted','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst($s) }}</option>@endforeach</select><input type="date" name="date_from" value="{{ request('date_from') }}"><input type="date" name="date_to" value="{{ request('date_to') }}"><button class="qt-btn qt-btn-dark">Filter</button><a class="qt-btn qt-btn-light" href="{{ route('admin.quotations.index') }}">Reset</a></form>
<div class="qt-panel"><div class="qt-panel-head"><div><span>QUOTATION PIPELINE</span><h2>All Quotations</h2></div><span>{{ $quotations->total() }} records</span></div>
@if($quotations->count())<div class="qt-table-wrap"><table class="qt-list"><thead><tr><th>Quotation</th><th>Customer</th><th>Date</th><th>Valid Until</th><th>Items</th><th>Amount</th><th>Status</th><th>Created By</th><th></th></tr></thead><tbody>@foreach($quotations as $q)<tr><td><a href="{{ route('admin.quotations.show',$q) }}"><strong>{{ $q->quotation_number }}</strong></a></td><td><strong>{{ $q->customer->business_name }}</strong><small>{{ $q->customer->customer_code }}</small></td><td>{{ $q->quotation_date?->format('d M Y') }}</td><td>{{ $q->valid_until?->format('d M Y') ?? '—' }}</td><td>{{ $q->items_count }}</td><td><strong>₹{{ number_format($q->grand_total,2) }}</strong></td><td><span class="qt-status qt-status-{{ $q->status }}">{{ ucfirst(str_replace('_',' ',$q->status)) }}</span></td><td>{{ $q->creator?->name ?? '—' }}</td><td><div class="qt-row-actions"><a href="{{ route('admin.quotations.show',$q) }}">View</a><a href="{{ route('admin.quotations.edit',$q) }}">Edit</a></div></td></tr>@endforeach</tbody></table></div><div class="qt-pagination">{{ $quotations->links() }}</div>@else<div class="qt-empty"><div>QT</div><h3>No quotations yet</h3><p>Create your first quotation for a customer.</p><a class="qt-btn qt-btn-primary" href="{{ route('admin.quotations.create') }}">+ New Quotation</a></div>@endif</div></div>
@endsection
