<!doctype html><html><head><meta charset="utf-8"><title>{{ $quotation->quotation_number }}</title><style>
*{box-sizing:border-box}body{font-family:DejaVu Sans,Arial,sans-serif;color:#172033;font-size:10px;margin:32px}.head{display:flex;justify-content:space-between;border-bottom:2px solid #111827;padding-bottom:18px}.brand{font-size:25px;font-weight:900}.tag{font-size:9px;letter-spacing:1.4px;color:#7c8799;margin-top:4px}.meta{text-align:right;color:#66758b;line-height:1.7}.meta strong{display:block;color:#172033;font-size:14px}.parties{display:flex;gap:15px;margin:22px 0}.party{width:50%;border:1px solid #e1e6ee;padding:13px;border-radius:7px}.label{font-size:8px;letter-spacing:1px;color:#7b8798;font-weight:bold}.party strong,.party span{display:block;margin-top:5px}.party span{color:#68758a}.items{width:100%;border-collapse:collapse}.items th,.items td{padding:9px 7px;border-bottom:1px solid #e4e8ee;text-align:left}.items th{font-size:8px;color:#7b8798;text-transform:uppercase}.totals{width:270px;margin:20px 0 0 auto}.totals div{display:flex;justify-content:space-between;padding:6px 0}.grand{border-top:2px solid #111827;margin-top:6px;padding-top:10px;font-size:14px;font-weight:bold}.notes{display:flex;gap:20px;margin-top:28px}.notes>div{width:50%}.notes p{line-height:1.55;color:#66758b}.footer{margin-top:30px;border-top:1px solid #e4e8ee;padding-top:12px;text-align:center;color:#8a95a7;font-size:9px}
</style></head><body>
<div class="head"><div><div class="brand">JALVAN</div><div class="tag">CUSTOM BRANDED WATER BOTTLES</div></div><div class="meta"><strong>{{ $quotation->quotation_number }}</strong>Date: {{ $quotation->quotation_date?->format('d M Y') }}<br>Valid until: {{ $quotation->valid_until?->format('d M Y') ?? 'No expiry' }}</div></div>
<div class="parties"><div class="party"><div class="label">QUOTATION FOR</div><strong>{{ $quotation->customer->business_name }}</strong><span>{{ $quotation->customer->customer_code }}</span><span>{{ $quotation->customer->address }}{{ $quotation->customer->city ? ', '.$quotation->customer->city : '' }}</span></div><div class="party"><div class="label">PREPARED BY</div><strong>{{ $quotation->creator?->name ?? 'JALVAN' }}</strong><span>{{ $quotation->created_at?->format('d M Y') }}</span></div></div>
<table class="items"><thead><tr><th>Product</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead><tbody>@foreach($quotation->items as $item)<tr><td>{{ $item->product?->name ?? 'Custom item' }}</td><td>{{ $item->description }}</td><td>{{ rtrim(rtrim(number_format($item->quantity,3), '0'), '.') }} {{ $item->unit }}</td><td>₹{{ number_format($item->unit_price,2) }}</td><td><strong>₹{{ number_format($item->line_total,2) }}</strong></td></tr>@endforeach</tbody></table>
<div class="totals"><div><span>Subtotal</span><strong>₹{{ number_format($quotation->subtotal,2) }}</strong></div><div><span>Discount</span><strong>− ₹{{ number_format($quotation->discount_amount,2) }}</strong></div><div><span>Tax</span><strong>₹{{ number_format($quotation->tax_amount,2) }}</strong></div><div><span>Shipping / Other</span><strong>₹{{ number_format($quotation->shipping_amount+$quotation->other_amount,2) }}</strong></div><div class="grand"><span>Grand Total</span><strong>₹{{ number_format($quotation->grand_total,2) }}</strong></div></div>
<div class="notes"><div><div class="label">NOTES</div><p>{{ $quotation->notes ?: '—' }}</p></div><div><div class="label">TERMS & CONDITIONS</div><p>{!! nl2br(e($quotation->terms_conditions ?: '—')) !!}</p></div></div><div class="footer">Thank you for your business. · JALVAN Custom Branded Water Bottles</div>
</body></html>
