@extends('layouts.admin')
@section('title',$quotation->quotation_number.' — JALVAN ERP')
@section('page_title','Quotation')
@section('breadcrumb','Sales / Quotations / '.$quotation->quotation_number)
@push('styles')<link rel="stylesheet" href="{{ asset('css/quotation.css') }}">@endpush
@section('content')
<div class="qt-page"><div class="qt-hero"><div><span class="qt-kicker">{{ $quotation->quotation_number }}</span><h1>{{ $quotation->customer->business_name }}</h1><p>{{ $quotation->quotation_date?->format('d M Y') }} · {{ $quotation->items->count() }} items · ₹{{ number_format($quotation->grand_total,2) }}</p></div><div class="qt-hero-actions"><a class="qt-btn qt-btn-light" href="{{ route('admin.quotations.index') }}">← Back</a>@if($quotation->isEditable())<a class="qt-btn qt-btn-dark" href="{{ route('admin.quotations.edit',$quotation) }}">Edit</a>@endif<a class="qt-btn qt-btn-light" href="{{ route('admin.quotations.preview',$quotation) }}">Preview</a><a class="qt-btn qt-btn-primary" href="{{ route('admin.quotations.pdf',$quotation) }}">PDF</a></div></div>
<div class="qt-detail-grid"><div class="qt-panel"><div class="qt-panel-head"><div><span>QUOTATION</span><h2>{{ $quotation->quotation_number }}</h2></div><span class="qt-status qt-status-{{ $quotation->status }}">{{ ucfirst($quotation->status) }}</span></div><div class="qt-customer-detail"><div><span>Customer</span><strong>{{ $quotation->customer->business_name }}</strong><small>{{ $quotation->customer->customer_code }}</small></div><div><span>Contact</span><strong>{{ $quotation->customer->user?->name ?? '—' }}</strong><small>{{ $quotation->customer->user?->mobile ?? '—' }}</small></div><div><span>Validity</span><strong>{{ $quotation->valid_until?->format('d M Y') ?? 'No expiry' }}</strong><small>Quotation date {{ $quotation->quotation_date?->format('d M Y') }}</small></div></div>
@if($quotation->design)<div class="qt-linked-card"><span>DESIGN STUDIO</span><strong>{{ $quotation->design->design_code }} · {{ $quotation->design->title }}</strong><small>Status: {{ ucfirst($quotation->design->status) }}</small></div>@endif
<div class="qt-table-wrap"><table class="qt-list qt-detail-items"><thead><tr><th>Product</th><th>Description</th><th>Qty</th><th>Price</th><th>Discount</th><th>Tax</th><th>Total</th></tr></thead><tbody>@foreach($quotation->items as $item)<tr><td><strong>{{ $item->product?->name ?? 'Custom item' }}</strong><small>{{ $item->product?->sku ?? '' }}</small></td><td>{{ $item->description }}</td><td>{{ rtrim(rtrim(number_format($item->quantity,3), '0'), '.') }} {{ $item->unit }}</td><td>₹{{ number_format($item->unit_price,2) }}</td><td>₹{{ number_format($item->discount_amount,2) }}</td><td>₹{{ number_format($item->tax_amount,2) }}</td><td><strong>₹{{ number_format($item->line_total,2) }}</strong></td></tr>@endforeach</tbody></table></div></div>
<aside class="qt-side-summary"><div class="qt-total-card"><div><span>Subtotal</span><strong>₹{{ number_format($quotation->subtotal,2) }}</strong></div><div><span>Discount</span><strong>− ₹{{ number_format($quotation->discount_amount,2) }}</strong></div><div><span>Tax</span><strong>₹{{ number_format($quotation->tax_amount,2) }}</strong></div><div><span>Shipping</span><strong>₹{{ number_format($quotation->shipping_amount,2) }}</strong></div><div><span>Other</span><strong>₹{{ number_format($quotation->other_amount,2) }}</strong></div><div class="qt-grand"><span>Grand Total</span><strong>₹{{ number_format($quotation->grand_total,2) }}</strong></div></div>
<div class="qt-panel qt-actions-panel"><span class="qt-kicker">WORKFLOW</span><div class="qt-workflow"><b class="{{ in_array($quotation->status,['draft','sent','viewed','approved','converted'])?'done':'' }}">Draft</b><i>→</i><b class="{{ in_array($quotation->status,['sent','viewed','approved','converted'])?'done':'' }}">Sent</b><i>→</i><b class="{{ in_array($quotation->status,['approved','converted'])?'done':'' }}">Approved</b><i>→</i><b class="{{ $quotation->status==='converted'?'done':'' }}">Order</b></div>
<div class="qt-action-stack">@if(in_array($quotation->status,['draft','viewed']))<form method="POST" action="{{ route('admin.quotations.send',$quotation) }}">@csrf<button class="qt-btn qt-btn-dark">Send Quotation →</button></form>@endif @if(in_array($quotation->status,['sent','viewed']))<form method="POST" action="{{ route('admin.quotations.approve',$quotation) }}">@csrf<button class="qt-btn qt-btn-primary">Approve</button></form><form method="POST" action="{{ route('admin.quotations.reject',$quotation) }}">@csrf<button class="qt-btn qt-btn-light">Reject</button></form>@endif @if($quotation->isConvertible())<form method="POST" action="{{ route('admin.quotations.convert',$quotation) }}">@csrf<button class="qt-btn qt-btn-primary">Convert to Order →</button></form>@endif<form method="POST" action="{{ route('admin.quotations.duplicate',$quotation) }}">@csrf<button class="qt-btn qt-btn-light">Duplicate</button></form></div></div></aside></div>
<div class="qt-note-grid"><div class="qt-panel"><span class="qt-kicker">NOTES</span><p>{{ $quotation->notes ?: 'No notes added.' }}</p></div><div class="qt-panel"><span class="qt-kicker">TERMS & CONDITIONS</span><p>{!! nl2br(e($quotation->terms_conditions ?: 'No terms added.')) !!}</p></div></div></div>
@endsection
