@extends('layouts.admin')
@section('title',$supplier->business_name)
@section('page_title','Supplier')
@section('breadcrumb','Procurement / Suppliers / '.$supplier->supplier_code)
@push('styles')<link rel="stylesheet" href="{{ asset('css/supplier-purchase.css') }}">@endpush
@section('content')<div class="sp-shell"><div class="sp-head"><div><div class="sp-kicker">SUPPLIER {{ $supplier->supplier_code }}</div><h1>{{ $supplier->business_name }}</h1><p>{{ $supplier->contact_name ?: 'Vendor' }} · {{ $supplier->mobile ?: 'No mobile' }}</p></div><div class="sp-actions"><a class="sp-btn" href="{{ route('admin.suppliers.index') }}">← Suppliers</a><a class="sp-btn" href="{{ route('admin.suppliers.edit',$supplier) }}">Edit</a><a class="sp-btn sp-primary" href="{{ route('admin.purchases.create',['supplier'=>$supplier->id]) }}">+ New Purchase</a></div></div>
<div class="sp-stats"><div><span>Purchase Value</span><b>₹{{ number_format($purchased,2) }}</b></div><div><span>Paid</span><b>₹{{ number_format($paid,2) }}</b></div><div><span>Outstanding</span><b>₹{{ number_format(max(0,$purchased-$paid),2) }}</b></div><div><span>Terms</span><b>{{ $supplier->payment_terms_days }} days</b></div></div>
<div class="sp-two"><div class="sp-card"><div class="sp-card-head"><div><div class="sp-kicker">PROFILE</div><h2>Contact & address</h2></div></div><div class="sp-detail-grid"><div><span>Contact</span><b>{{ $supplier->contact_name ?: '—' }}</b></div><div><span>Mobile</span><b>{{ $supplier->mobile ?: '—' }}</b></div><div><span>Email</span><b>{{ $supplier->email ?: '—' }}</b></div><div><span>GSTIN</span><b>{{ $supplier->gstin ?: '—' }}</b></div><div class="sp-span-2"><span>Address</span><b>{{ collect([$supplier->address,$supplier->city,$supplier->state,$supplier->pincode])->filter()->implode(', ') ?: '—' }}</b></div></div></div>
<div class="sp-card"><div class="sp-kicker">NOTES</div><p>{{ $supplier->notes ?: 'No supplier notes.' }}</p></div></div>
<div class="sp-card"><div class="sp-card-head"><div><div class="sp-kicker">RECENT PROCUREMENT</div><h2>Purchase History</h2></div></div><div class="sp-table-wrap"><table class="sp-table"><thead><tr><th>Purchase</th><th>Date</th><th>Status</th><th>Total</th><th>Balance</th><th></th></tr></thead><tbody>@forelse($supplier->purchases as $p)<tr><td><strong>{{ $p->purchase_number }}</strong></td><td>{{ $p->purchase_date?->format('d M Y') }}</td><td><span class="sp-status {{ $p->status }}">{{ ucwords(str_replace('_',' ',$p->status)) }}</span></td><td>₹{{ number_format((float)$p->grand_total,2) }}</td><td>₹{{ number_format((float)$p->balance_amount,2) }}</td><td><a class="sp-link" href="{{ route('admin.purchases.show',$p) }}">View →</a></td></tr>@empty<tr><td colspan="6">No purchases recorded.</td></tr>@endforelse</tbody></table></div></div>
</div>@endsection
