@php
    $purchase = $purchase ?? null;

    $editing = $purchase !== null;

    $oldItems = old('items');

    $items = $oldItems !== null
        ? $oldItems
        : ($editing
            ? $purchase->items->map(fn ($i) => $i->toArray())->all()
            : [[]]);
@endphp
<div class="sp-purchase-form" id="purchaseFormRoot">
<div class="sp-card"><div class="sp-card-head"><div><div class="sp-kicker">PURCHASE HEADER</div><h2>Purchase details</h2></div><span class="sp-doc">{{ $editing ? $purchase?->purchase_number : 'Auto generated on save' }}</span></div><div class="sp-form-grid"><label>Supplier *<select name="supplier_id" required><option value="">Select supplier</option>@foreach($suppliers as $s)<option value="{{ $s->id }}" @selected((string)old('supplier_id',$purchase?->supplier_id ?? request('supplier'))===(string)$s->id)>{{ $s->business_name }} · {{ $s->supplier_code }}</option>@endforeach</select></label><label>Purchase Date *<input type="date" name="purchase_date" value="{{ old('purchase_date', $purchase?->purchase_date?->format('Y-m-d') ?? now()->toDateString()) }}" required></label><label>Expected Date<input type="date" name="expected_date" value="{{ old('expected_date',$purchase?->expected_date?->format('Y-m-d') ?? '') }}"></label><label>Status<select name="status"><option value="draft" @selected(old('status',$purchase?->status ?? 'draft')==='draft')>Draft</option><option value="ordered" @selected(old('status',$purchase?->status ?? '')==='ordered')>Ordered</option></select></label></div></div>
<div class="sp-card"><div class="sp-card-head"><div><div class="sp-kicker">LINE ITEMS</div><h2>What are you purchasing?</h2></div><button type="button" class="sp-btn sp-primary" data-add-purchase-item>+ Add Item</button></div><div class="sp-table-wrap"><table class="sp-table sp-purchase-table"><thead><tr><th>Product / Inventory</th><th>Description</th><th>Qty</th><th>Unit</th><th>Unit Cost</th><th>Discount</th><th>Tax %</th><th>Total</th><th></th></tr></thead><tbody id="purchaseItemsBody">
@foreach($items as $idx=>$item)<tr class="sp-item-row"><td><select name="items[{{ $idx }}][product_id]" class="js-product"><option value="">Product</option>@foreach($products as $p)<option value="{{ $p->id }}" data-unit="{{ $p->unit }}" @selected((string)($item['product_id']??'')===(string)$p->id)>{{ $p->name }} · {{ $p->sku }}</option>@endforeach</select><select name="items[{{ $idx }}][inventory_item_id]" class="js-inventory"><option value="">Inventory item</option>@foreach($inventoryItems as $inv)<option value="{{ $inv->id }}" data-unit="{{ $inv->unit }}" @selected((string)($item['inventory_item_id']??'')===(string)$inv->id)>{{ $inv->name }} · {{ $inv->sku }}</option>@endforeach</select></td><td><input name="items[{{ $idx }}][description]" value="{{ $item['description']??'' }}" placeholder="Bottle / cap / label..."></td><td><input class="js-qty" type="number" min="0.001" step="0.001" name="items[{{ $idx }}][quantity]" value="{{ $item['quantity']??1 }}"></td><td><input class="js-unit" name="items[{{ $idx }}][unit]" value="{{ $item['unit']??'unit' }}"></td><td><input class="js-price" type="number" min="0" step="0.01" name="items[{{ $idx }}][unit_price]" value="{{ $item['unit_price']??0 }}"></td><td><div class="sp-discount-cell"><select class="js-discount-type" name="items[{{ $idx }}][discount_type]"><option value="">—</option><option value="percent" @selected(($item['discount_type']??'')==='percent')>%</option><option value="fixed" @selected(($item['discount_type']??'')==='fixed')>₹</option></select><input class="js-discount" type="number" min="0" step="0.01" name="items[{{ $idx }}][discount_value]" value="{{ $item['discount_value']??0 }}"></div></td><td><input class="js-tax" type="number" min="0" max="100" step="0.01" name="items[{{ $idx }}][tax_rate]" value="{{ $item['tax_rate']??0 }}"></td><td class="js-line-total">₹0.00</td><td><button type="button" class="sp-icon-btn" data-duplicate-item title="Duplicate">⧉</button><button type="button" class="sp-icon-btn danger" data-remove-item title="Remove">×</button></td></tr>@endforeach
</tbody></table></div></div>
<div class="sp-purchase-grid"><div class="sp-card"><div class="sp-card-head"><div><div class="sp-kicker">CHARGES</div><h2>Adjustments</h2></div></div><div class="sp-form-grid"><label>Overall Discount<select name="discount_type"><option value="">None</option><option value="percent" @selected(old('discount_type',$purchase->discount_type??'')==='percent')>Percentage</option><option value="fixed" @selected(old('discount_type',$purchase->discount_type??'')==='fixed')>Fixed ₹</option></select></label><label>Discount Value<input id="overallDiscount" type="number" min="0" step="0.01" name="discount_value" value="{{ old('discount_value',$purchase->discount_value??0) }}"></label><label>Overall Tax %<input id="overallTax" type="number" min="0" max="100" step="0.01" name="tax_rate" value="{{ old('tax_rate',$purchase->tax_rate??0) }}"></label><label>Shipping<input id="shipping" type="number" min="0" step="0.01" name="shipping_amount" value="{{ old('shipping_amount',$purchase->shipping_amount??0) }}"></label><label>Other Charges<input id="other" type="number" min="0" step="0.01" name="other_amount" value="{{ old('other_amount',$purchase->other_amount??0) }}"></label></div></div><div class="sp-card sp-total-card"><div class="sp-kicker">PURCHASE TOTAL</div><div class="sp-total-row"><span>Subtotal</span><b id="subtotal">₹0.00</b></div><div class="sp-total-row"><span>Discount</span><b id="discountTotal">− ₹0.00</b></div><div class="sp-total-row"><span>Tax</span><b id="taxTotal">₹0.00</b></div><div class="sp-total-row"><span>Shipping</span><b id="shippingTotal">₹0.00</b></div><div class="sp-total-row"><span>Other</span><b id="otherTotal">₹0.00</b></div><div class="sp-grand"><span>Grand Total</span><strong id="grandTotal">₹0.00</strong></div></div></div>
<div class="sp-card"><div class="sp-form-grid"><label class="sp-span-2">Notes<textarea name="notes" rows="4" placeholder="Internal procurement notes...">{{ old('notes',$purchase->notes??'') }}</textarea></label><label class="sp-span-2">Terms & Conditions<textarea name="terms_conditions" rows="4" placeholder="Payment terms, delivery terms, quality conditions...">{{ old('terms_conditions',$purchase->terms_conditions??'') }}</textarea></label></div></div>
<div class="sp-form-actions"><a class="sp-btn" href="{{ route('admin.purchases.index') }}">Cancel</a><button class="sp-btn sp-primary">{{ $editing ? 'Update Purchase' : 'Save Purchase' }}</button></div>
</div>
