@extends('layouts.admin')
@section('title','Purchases')
@section('page_title','Purchases')
@section('breadcrumb','Procurement / Purchases')
@push('styles')<link rel="stylesheet" href="{{ asset('css/supplier-purchase.css') }}">@endpush
@section('content')
<div class="sp-shell">
@if(session('success'))<div class="sp-alert sp-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="sp-alert sp-error">{{ $errors->first() }}</div>@endif
<div class="sp-head"><div><div class="sp-kicker">PROCUREMENT</div><h1>Purchases</h1><p>Track supplier purchases, stock receipts and payables.</p></div><a class="sp-btn sp-primary" href="{{ route('admin.purchases.create') }}">+ New Purchase</a></div>
<div class="sp-stats"><div><span>Total Purchases</span><b>{{ $stats['total'] }}</b></div><div><span>Drafts</span><b>{{ $stats['draft'] }}</b></div><div><span>Open Orders</span><b>{{ $stats['ordered'] }}</b></div><div><span>Received</span><b>{{ $stats['received'] }}</b></div><div><span>Purchase Value</span><b>₹{{ number_format($stats['value'],2) }}</b></div><div><span>Payables</span><b>₹{{ number_format($stats['due'],2) }}</b></div></div>
<form class="sp-filters" method="GET"><input name="q" value="{{ request('q') }}" placeholder="Search purchase, supplier, mobile..."><select name="status"><option value="">All Status</option>@foreach(['draft','ordered','partially_received','received','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><select name="supplier_id"><option value="">All Suppliers</option>@foreach($suppliers as $s)<option value="{{ $s->id }}" @selected((string)request('supplier_id')===(string)$s->id)>{{ $s->business_name }}</option>@endforeach</select><input type="date" name="from" value="{{ request('from') }}"><input type="date" name="to" value="{{ request('to') }}"><button class="sp-btn sp-primary">Search</button><a class="sp-btn" href="{{ route('admin.purchases.index') }}">Reset</a></form>
<div class="sp-card"><div class="sp-card-head"><div><div class="sp-kicker">PURCHASE PIPELINE</div><h2>All Purchases</h2></div><span>{{ $purchases->total() }} records</span></div><div class="sp-table-wrap"><table class="sp-table"><thead><tr><th>Purchase</th><th>Supplier</th><th>Date</th><th>Items</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>@forelse($purchases as $p)<tr><td><strong>{{ $p->purchase_number }}</strong><small>{{ $p->creator?->name ?? 'System' }}</small></td><td>{{ $p->supplier->business_name }}<small>{{ $p->supplier->supplier_code }}</small></td><td>{{ $p->purchase_date?->format('d M Y') }}</td><td>{{ $p->items_count }}</td><td>₹{{ number_format((float)$p->grand_total,2) }}</td><td>₹{{ number_format((float)$p->paid_amount,2) }}</td><td>₹{{ number_format((float)$p->balance_amount,2) }}</td><td><span class="sp-status {{ $p->status }}">{{ ucwords(str_replace('_',' ',$p->status)) }}</span></td><td><a class="sp-link" href="{{ route('admin.purchases.show',$p) }}">View →</a></td></tr>@empty<tr><td colspan="9"><div class="sp-empty"><b>No purchases yet</b><span>Record your first supplier purchase to start procurement tracking.</span><a class="sp-btn sp-primary" href="{{ route('admin.purchases.create') }}">+ New Purchase</a></div></td></tr>@endforelse</tbody></table></div><div class="sp-pagination">{{ $purchases->links() }}</div></div>
</div>@endsection
