@extends('layouts.admin')
@section('title',$purchase->purchase_number)
@section('page_title','Purchase')
@section('breadcrumb','Procurement / Purchases / '.$purchase->purchase_number)
@push('styles')<link rel="stylesheet" href="{{ asset('css/supplier-purchase.css') }}">@endpush
@section('content')
<div class="sp-shell" data-purchase-show>
@if(session('success'))<div class="sp-alert sp-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="sp-alert sp-error">{{ $errors->first() }}</div>@endif
<div class="sp-head"><div><div class="sp-kicker">PURCHASE DOCUMENT</div><h1>{{ $purchase->purchase_number }}</h1><p>{{ $purchase->supplier->business_name }} · {{ $purchase->purchase_date?->format('d M Y') }}</p></div><div class="sp-actions"><a class="sp-btn" href="{{ route('admin.purchases.index') }}">← Purchases</a>@can('update',$purchase)<a class="sp-btn" href="{{ route('admin.purchases.edit',$purchase) }}">Edit</a>@endcan@can('create',App\Models\Purchase::class)<form method="POST" action="{{ route('admin.purchases.duplicate',$purchase) }}">@csrf<button class="sp-btn">Duplicate</button></form>@endcan@can('export',$purchase)<a class="sp-btn" target="_blank" href="{{ route('admin.purchases.pdf',$purchase) }}">PDF / Print</a>@endcan</div></div>
<div class="sp-stats"><div><span>Status</span><b><span class="sp-status {{ $purchase->status }}">{{ ucwords(str_replace('_',' ',$purchase->status)) }}</span></b></div><div><span>Grand Total</span><b>₹{{ number_format((float)$purchase->grand_total,2) }}</b></div><div><span>Paid</span><b>₹{{ number_format((float)$purchase->paid_amount,2) }}</b></div><div><span>Balance</span><b>₹{{ number_format((float)$purchase->balance_amount,2) }}</b></div></div>
<div class="sp-two"><div class="sp-card"><div class="sp-card-head"><div><div class="sp-kicker">SUPPLIER</div><h2>{{ $purchase->supplier->business_name }}</h2></div></div><div class="sp-detail-grid"><div><span>Code</span><b>{{ $purchase->supplier->supplier_code }}</b></div><div><span>Contact</span><b>{{ $purchase->supplier->contact_name ?: '—' }}</b></div><div><span>Mobile</span><b>{{ $purchase->supplier->mobile ?: '—' }}</b></div><div><span>GSTIN</span><b>{{ $purchase->supplier->gstin ?: '—' }}</b></div><div class="sp-span-2"><span>Address</span><b>{{ collect([$purchase->supplier->address,$purchase->supplier->city,$purchase->supplier->state,$purchase->supplier->pincode])->filter()->implode(', ') ?: '—' }}</b></div></div></div><div class="sp-card"><div class="sp-kicker">SCHEDULE</div><p><strong>Purchase:</strong> {{ $purchase->purchase_date?->format('d M Y') }}</p><p><strong>Expected:</strong> {{ $purchase->expected_date?->format('d M Y') ?: '—' }}</p><p><strong>Created by:</strong> {{ $purchase->creator?->name ?: 'System' }}</p><p><strong>Payment:</strong> {{ ucfirst($purchase->payment_status) }}</p></div></div>
<div class="sp-card"><div class="sp-card-head"><div><div class="sp-kicker">PURCHASE ITEMS</div><h2>Items & stock receipt</h2></div></div><div class="sp-table-wrap"><table class="sp-table"><thead><tr><th>Item</th><th>Qty</th><th>Received</th><th>Unit Cost</th><th>Tax</th><th>Total</th></tr></thead><tbody>@foreach($purchase->items as $i)<tr><td><strong>{{ $i->description }}</strong><small>{{ $i->product?->name ?? $i->inventoryItem?->name ?? 'Inventory item not linked' }}</small></td><td>{{ $i->quantity }} {{ $i->unit }}</td><td>{{ $i->received_quantity }} {{ $i->unit }}</td><td>₹{{ number_format((float)$i->unit_price,2) }}</td><td>₹{{ number_format((float)$i->tax_amount,2) }}</td><td>₹{{ number_format((float)$i->line_total,2) }}</td></tr>@endforeach</tbody></table></div></div>
<div class="sp-purchase-grid"><div class="sp-card"><div class="sp-kicker">STOCK RECEIPT</div>@can('receive',$purchase)<p>Receive only the quantity actually delivered. Stock will be posted through the existing InventoryService.</p><form method="POST" action="{{ route('admin.purchases.receive',$purchase) }}">@csrf<div class="sp-receive-list">@foreach($purchase->items as $i)<label><span>{{ $i->description }}<small>Remaining: {{ number_format(max(0,(float)$i->quantity-(float)$i->received_quantity),3) }} {{ $i->unit }}</small></span><input type="number" step="0.001" min="0" max="{{ max(0,(float)$i->quantity-(float)$i->received_quantity) }}" name="quantities[{{ $i->id }}]" value="0"></label>@endforeach</div><button class="sp-btn sp-primary">Receive Stock</button></form>@else<p class="sp-muted">No stock receipt action available for this purchase.</p>@endcan</div>
<div class="sp-card"><div class="sp-kicker">SUPPLIER PAYMENT</div>@can('pay',$purchase)<form method="POST" action="{{ route('admin.purchases.pay',$purchase) }}" class="sp-payment-form">@csrf<label>Date<input type="date" name="payment_date" value="{{ now()->toDateString() }}" required></label><label>Amount<input type="number" name="amount" step="0.01" min="0.01" max="{{ $purchase->balance_amount }}" value="{{ $purchase->balance_amount }}" required></label><label>Method<select name="method"><option>bank_transfer</option><option>upi</option><option>cash</option><option>cheque</option><option>other</option></select></label><label>Reference<input name="reference" placeholder="UTR / transaction reference"></label><button class="sp-btn sp-primary">Record Payment</button></form>@else<p class="sp-muted">No outstanding balance.</p>@endcan</div></div>
<div class="sp-card"><div class="sp-kicker">TOTALS</div><div class="sp-total-row"><span>Subtotal</span><b>₹{{ number_format((float)$purchase->subtotal,2) }}</b></div><div class="sp-total-row"><span>Discount</span><b>− ₹{{ number_format((float)$purchase->discount_amount,2) }}</b></div><div class="sp-total-row"><span>Tax</span><b>₹{{ number_format((float)$purchase->tax_amount,2) }}</b></div><div class="sp-total-row"><span>Shipping</span><b>₹{{ number_format((float)$purchase->shipping_amount,2) }}</b></div><div class="sp-total-row"><span>Other</span><b>₹{{ number_format((float)$purchase->other_amount,2) }}</b></div><div class="sp-grand"><span>Grand Total</span><strong>₹{{ number_format((float)$purchase->grand_total,2) }}</strong></div></div>
<div class="sp-two"><div class="sp-card"><div class="sp-kicker">NOTES</div><p>{{ $purchase->notes ?: 'No notes.' }}</p></div><div class="sp-card"><div class="sp-kicker">TERMS & CONDITIONS</div><p>{{ $purchase->terms_conditions ?: 'No terms added.' }}</p></div></div>
@if($purchase->payments->count())<div class="sp-card"><div class="sp-card-head"><div><div class="sp-kicker">PAYMENT HISTORY</div><h2>Supplier payments</h2></div></div><div class="sp-table-wrap"><table class="sp-table"><thead><tr><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>By</th></tr></thead><tbody>@foreach($purchase->payments as $pay)<tr><td>{{ $pay->payment_date?->format('d M Y') }}</td><td>₹{{ number_format((float)$pay->amount,2) }}</td><td>{{ ucwords(str_replace('_',' ',$pay->method)) }}</td><td>{{ $pay->reference ?: '—' }}</td><td>{{ $pay->creator?->name ?: 'System' }}</td></tr>@endforeach</tbody></table></div></div>@endif
@if(!in_array($purchase->status,['received','cancelled']))@can('cancel',$purchase)<form method="POST" action="{{ route('admin.purchases.cancel',$purchase) }}" onsubmit="return confirm('Cancel this purchase?')">@csrf<button class="sp-btn sp-danger">Cancel Purchase</button></form>@endcan@endif
</div>
@endsection
