@extends('layouts.admin')
@section('title','Deliveries')
@section('page_title','Deliveries')
@section('breadcrumb','Delivery / Deliveries')
@push('styles')<link rel="stylesheet" href="{{ asset('css/delivery.css') }}">@endpush
@section('content')
<div class="dlv-page">
 <div class="dlv-page-head"><div><span class="dlv-kicker">DELIVERY · FULFILMENT</span><h1>Deliveries</h1><p>Dispatch branded bottles, capture proof and maintain batch traceability.</p></div><a class="dlv-btn dlv-dark" href="{{ route('admin.deliveries.create') }}">+ New Delivery</a></div>
 <div class="dlv-stats">
 @foreach([['Total',$stats['total'],'All delivery records'],['Ready',$stats['ready'],'Ready to dispatch'],['Out for Delivery',$stats['out'],'Currently on route'],['Delivered',$stats['delivered'],'Completed'],['Failed',$stats['failed'],'Needs follow-up'],['Cancelled',$stats['cancelled'],'Cancelled records']] as $s)<a class="dlv-stat" href="{{ route('admin.deliveries.index',$s[0]==='Total'?[]:['status'=>strtolower(str_replace(' ','_',$s[0]))]) }}"><span>{{ $s[0] }}</span><b>{{ $s[1] }}</b><small>{{ $s[2] }}</small></a>@endforeach
 </div>
 <form method="GET" class="dlv-filter"><div><span>⌕</span><input name="q" value="{{ request('q') }}" placeholder="Search delivery, order, customer, mobile..."></div><select name="status"><option value="">All Status</option>@foreach(['ready','out_for_delivery','delivered','failed','cancelled'] as $st)<option value="{{ $st }}" @selected(request('status')===$st)>{{ ucwords(str_replace('_',' ',$st)) }}</option>@endforeach</select><select name="customer_id"><option value="">All Customers</option>@foreach($customers as $c)<option value="{{ $c->id }}" @selected((string)request('customer_id')===(string)$c->id)>{{ $c->business_name }}</option>@endforeach</select><input type="date" name="date_from" value="{{ request('date_from') }}"><input type="date" name="date_to" value="{{ request('date_to') }}"><button class="dlv-btn dlv-dark">Search</button><a class="dlv-btn" href="{{ route('admin.deliveries.index') }}">Reset</a></form>
 <section class="dlv-list-card"><div class="dlv-list-head"><div><span class="dlv-kicker">FULFILMENT PIPELINE</span><h2>All Deliveries</h2><small>{{ $deliveries->total() }} records</small></div></div>
 @if($deliveries->count())<div class="dlv-table-wrap"><table class="dlv-list"><thead><tr><th>Delivery</th><th>Customer</th><th>Order</th><th>Date</th><th>Items</th><th>Assigned</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach($deliveries as $d)<tr><td><a class="dlv-number" href="{{ route('admin.deliveries.show',$d) }}">{{ $d->delivery_number }}</a></td><td><strong>{{ $d->customer->business_name }}</strong><small>{{ $d->customer->customer_code }}</small></td><td>{{ $d->order->order_number }}</td><td>{{ $d->delivery_date?->format('d M Y') }}<small>{{ $d->scheduled_date ? 'Scheduled '.$d->scheduled_date->format('d M') : '' }}</small></td><td>{{ $d->items_count }}</td><td>{{ $d->assignee?->name ?? 'Unassigned' }}</td><td><span class="dlv-badge dlv-{{ $d->status }}">{{ ucwords(str_replace('_',' ',$d->status)) }}</span></td><td><div class="dlv-actions"><a href="{{ route('admin.deliveries.show',$d) }}">View</a>@if($d->canEdit())<a href="{{ route('admin.deliveries.edit',$d) }}">Edit</a>@endif</div></td></tr>@endforeach</tbody></table></div><div class="dlv-pagination">{{ $deliveries->links() }}</div>@else<div class="dlv-empty"><div>✓</div><h3>No deliveries yet</h3><p>Create your first delivery from a confirmed order.</p><a class="dlv-btn dlv-dark" href="{{ route('admin.deliveries.create') }}">+ New Delivery</a></div>@endif
 </section>
</div>
@endsection
