@extends('layouts.admin')
@section('title',$delivery->delivery_number)
@section('page_title','Delivery')
@section('breadcrumb','Delivery / '.$delivery->delivery_number)
@push('styles')<link rel="stylesheet" href="{{ asset('css/delivery.css') }}">@endpush
@section('content')
<div class="dlv-page">
 <div class="dlv-page-head"><div><span class="dlv-kicker">DELIVERY CHALLAN</span><h1>{{ $delivery->delivery_number }}</h1><p>{{ $delivery->customer->business_name }} · {{ $delivery->order->order_number }}</p></div><div class="dlv-head-actions"><span class="dlv-badge dlv-{{ $delivery->status }}">{{ ucwords(str_replace('_',' ',$delivery->status)) }}</span><a class="dlv-btn" href="{{ route('admin.deliveries.print',$delivery) }}" target="_blank">Print</a>@if($delivery->canEdit())<a class="dlv-btn" href="{{ route('admin.deliveries.edit',$delivery) }}">Edit</a>@endif</div></div>
 <div class="dlv-action-bar">@if($delivery->canDispatch())<form method="POST" action="{{ route('admin.deliveries.dispatch',$delivery) }}">@csrf<button class="dlv-btn dlv-dark" onclick="return confirm('Dispatch this delivery? Stock will be issued and batches allocated.')">Dispatch →</button></form>@endif @if($delivery->canDeliver())<button class="dlv-btn dlv-dark" data-open-deliver>Mark Delivered ✓</button><button class="dlv-btn dlv-danger" data-open-fail>Mark Failed</button>@endif @if($delivery->canCancel())<form method="POST" action="{{ route('admin.deliveries.cancel',$delivery) }}">@csrf<button class="dlv-btn dlv-danger" onclick="return confirm('Cancel this delivery?')">Cancel</button></form>@endif</div>
 <div class="dlv-detail-grid"><main>
  <section class="dlv-card"><div class="dlv-card-head"><div><span class="dlv-kicker">CUSTOMER</span><h3>{{ $delivery->customer->business_name }}</h3></div></div><div class="dlv-info-grid"><div><span>Customer Code</span><strong>{{ $delivery->customer->customer_code }}</strong></div><div><span>Mobile</span><strong>{{ $delivery->customer->user?->mobile ?? '—' }}</strong></div><div><span>Order</span><strong>{{ $delivery->order->order_number }}</strong></div><div><span>Delivery Date</span><strong>{{ $delivery->delivery_date?->format('d M Y') }}</strong></div></div><div class="dlv-address"><strong>{{ $delivery->delivery_address ?: 'No address' }}</strong><span>{{ collect([$delivery->delivery_city,$delivery->delivery_state,$delivery->delivery_pincode])->filter()->implode(', ') }}</span></div></section>
  <section class="dlv-card"><div class="dlv-card-head"><div><span class="dlv-kicker">ITEMS & TRACEABILITY</span><h3>Delivered Products</h3></div></div><div class="dlv-table-wrap"><table class="dlv-detail-items"><thead><tr><th>Product</th><th>Batch</th><th>Planned</th><th>Delivered</th><th>Unit</th></tr></thead><tbody>@foreach($delivery->items as $i)<tr><td><strong>{{ $i->product?->name ?? $i->description }}</strong><small>{{ $i->product?->sku ?? '' }}</small></td><td>{{ $i->batch?->batch_number ?? 'Not assigned' }}</td><td>{{ rtrim(rtrim(number_format($i->quantity,3),'0'),'.') }}</td><td>{{ rtrim(rtrim(number_format($i->delivered_quantity,3),'0'),'.') }}</td><td>{{ $i->unit }}</td></tr>@endforeach</tbody></table></div></section>
  <section class="dlv-card"><div class="dlv-card-head"><div><span class="dlv-kicker">TRANSPORT</span><h3>Driver & Vehicle</h3></div></div><div class="dlv-info-grid"><div><span>Driver</span><strong>{{ $delivery->driver_name ?: '—' }}</strong></div><div><span>Driver Mobile</span><strong>{{ $delivery->driver_mobile ?: '—' }}</strong></div><div><span>Vehicle</span><strong>{{ $delivery->vehicle_number ?: '—' }}</strong></div><div><span>Assigned</span><strong>{{ $delivery->assignee?->name ?? '—' }}</strong></div></div></section>
 </main><aside>
  <section class="dlv-card dlv-sticky"><div class="dlv-side-card"><span>Workflow</span><div class="dlv-timeline"><div class="{{ in_array($delivery->status,['ready','out_for_delivery','delivered'])?'on':'' }}"><i></i><b>Ready</b></div><div class="{{ in_array($delivery->status,['out_for_delivery','delivered'])?'on':'' }}"><i></i><b>Out for Delivery</b></div><div class="{{ $delivery->status==='delivered'?'on':'' }}"><i></i><b>Delivered</b></div></div></div><div class="dlv-side-card"><span>Receiver</span><strong>{{ $delivery->receiver_name ?: 'Not received yet' }}</strong><small>{{ $delivery->receiver_mobile ?: '' }}</small></div><div class="dlv-side-card"><span>Dispatched</span><strong>{{ $delivery->dispatched_at?->format('d M Y, h:i A') ?? '—' }}</strong></div><div class="dlv-side-card"><span>Delivered</span><strong>{{ $delivery->delivered_at?->format('d M Y, h:i A') ?? '—' }}</strong></div>@if($delivery->failed_reason)<div class="dlv-side-card dlv-side-danger"><span>Failure Reason</span><p>{{ $delivery->failed_reason }}</p></div>@endif</section>
  @if($delivery->proof_path)<section class="dlv-card"><div class="dlv-side-card"><span>Proof of Delivery</span><img class="dlv-proof" src="{{ Storage::url($delivery->proof_path) }}" alt="Delivery proof"></div></section>@endif
 </aside></div>
</div>
@if($delivery->canDeliver())<div class="dlv-modal" id="deliverModal"><div class="dlv-modal-card"><button class="dlv-modal-close" data-close-modal>×</button><span class="dlv-kicker">COMPLETION</span><h3>Confirm delivery</h3><form method="POST" action="{{ route('admin.deliveries.status',$delivery) }}" enctype="multipart/form-data">@csrf<input type="hidden" name="action" value="deliver"><label class="dlv-field"><span>Receiver Name *</span><input name="receiver_name" required></label><label class="dlv-field"><span>Receiver Mobile</span><input name="receiver_mobile"></label>@foreach($delivery->items as $i)<label class="dlv-field"><span>{{ $i->product?->name ?? $i->description }} · Delivered Qty</span><input type="number" step="0.001" min="0" max="{{ $i->quantity }}" name="delivered_quantities[{{ $i->id }}]" value="{{ $i->quantity }}"></label>@endforeach<label class="dlv-field"><span>Proof Photo</span><input type="file" name="proof" accept="image/*"></label><label class="dlv-field"><span>Signature</span><input type="file" name="signature" accept="image/*"></label><button class="dlv-btn dlv-dark">Complete Delivery</button></form></div></div><div class="dlv-modal" id="failModal"><div class="dlv-modal-card"><button class="dlv-modal-close" data-close-modal>×</button><span class="dlv-kicker">EXCEPTION</span><h3>Mark delivery failed</h3><form method="POST" action="{{ route('admin.deliveries.status',$delivery) }}">@csrf<input type="hidden" name="action" value="fail"><label class="dlv-field"><span>Reason *</span><textarea name="failed_reason" rows="5" required></textarea></label><button class="dlv-btn dlv-danger">Mark Failed</button></form></div></div><script src="{{ asset('js/delivery.js') }}"></script>@endif
@endsection
