@php($staff = $staff ?? null)
@php($editing = (bool) $staff)
<div class="hr-form-grid">
<div class="hr-section"><h3>Basic Information</h3><div class="hr-fields"><label>Employee Code<input name="employee_code" value="{{ old('employee_code',$staff->employee_code ?? '') }}" placeholder="Auto-generated if blank"></label><label>First Name *<input name="first_name" required value="{{ old('first_name',$staff->first_name ?? '') }}"></label><label>Last Name<input name="last_name" value="{{ old('last_name',$staff->last_name ?? '') }}"></label><label>Email *<input type="email" name="email" required value="{{ old('email',$staff->email ?? '') }}"></label><label>Mobile *<input name="mobile" required value="{{ old('mobile',$staff->mobile ?? '') }}"></label><label>Date of Birth<input type="date" name="date_of_birth" value="{{ old('date_of_birth',optional($staff->date_of_birth ?? null)->format('Y-m-d')) }}"></label><label>Gender<select name="gender"><option value="">Select</option>@foreach(['male','female','other'] as $g)<option value="{{ $g }}" @selected(old('gender',$staff->gender ?? '')===$g)>{{ ucfirst($g) }}</option>@endforeach</select></label></div></div>
<div class="hr-section"><h3>Employment</h3><div class="hr-fields"><label>Designation<input name="designation" value="{{ old('designation',$staff->designation ?? '') }}"></label><label>Department<input name="department" value="{{ old('department',$staff->department ?? '') }}"></label><label>Joining Date *<input type="date" name="joining_date" required value="{{ old('joining_date',optional($staff->joining_date ?? null)->format('Y-m-d')) }}"></label><label>Employment Type<select name="employment_type">@foreach(['full_time','part_time','contract','intern'] as $t)<option value="{{ $t }}" @selected(old('employment_type',$staff->employment_type ?? 'full_time')===$t)>{{ ucwords(str_replace('_',' ',$t)) }}</option>@endforeach</select></label><label>Role *<select name="role_id" required><option value="">Select Role</option>@foreach($roles ?? [] as $role)<option value="{{ $role->id }}" @selected((string)old('role_id',$staff->user?->roles?->first()?->id ?? '')===(string)$role->id)>{{ $role->name }}</option>@endforeach</select></label><label>Monthly Salary<input type="number" step="0.01" min="0" name="salary" value="{{ old('salary',$staff->salary ?? '') }}"></label><label>Status<select name="status">@foreach(['active','inactive','on_leave','terminated'] as $s)<option value="{{ $s }}" @selected(old('status',$staff->status ?? 'active')===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select></label></div></div>
<div class="hr-section"><h3>Contact & Emergency</h3><div class="hr-fields"><label>Address<textarea name="address">{{ old('address',$staff->address ?? '') }}</textarea></label><label>City<input name="city" value="{{ old('city',$staff->city ?? '') }}"></label><label>State<input name="state" value="{{ old('state',$staff->state ?? '') }}"></label><label>Pincode<input name="pincode" value="{{ old('pincode',$staff->pincode ?? '') }}"></label><label>Emergency Contact Name<input name="emergency_contact_name" value="{{ old('emergency_contact_name',$staff->emergency_contact_name ?? '') }}"></label><label>Emergency Contact Mobile<input name="emergency_contact_mobile" value="{{ old('emergency_contact_mobile',$staff->emergency_contact_mobile ?? '') }}"></label></div></div>
<div class="hr-section"><h3>Notes</h3><textarea class="hr-full" name="notes" rows="4">{{ old('notes',$staff->notes ?? '') }}</textarea></div>
</div>
<div class="hr-form-footer"><a class="hr-btn" href="{{ $editing ? route('admin.staff.show',$staff) : route('admin.staff.index') }}">Cancel</a><button class="hr-btn hr-btn-primary">{{ $editing ? 'Update Staff' : 'Create Staff' }}</button></div>
