@extends('layouts.admin')
@push('styles')<link rel="stylesheet" href="{{ asset('css/staff-attendance.css') }}">@endpush
@section('content')
<div class="hr-head"><div><div class="hr-kicker">HR MANAGEMENT</div><h1>Staff</h1><p>Manage employees, roles, contact details and employment status.</p></div><a class="hr-btn hr-btn-primary" href="{{ route('admin.staff.create') }}">+ Add Staff</a></div>
@if(session('success'))<div class="hr-alert">{{ session('success') }}</div>@endif
<div class="hr-stats"><div><span>Total Staff</span><strong>{{ $stats['total'] }}</strong></div><div><span>Active</span><strong>{{ $stats['active'] }}</strong></div><div><span>On Leave</span><strong>{{ $stats['on_leave'] }}</strong></div><div><span>Inactive</span><strong>{{ $stats['inactive'] }}</strong></div></div>
<form class="hr-filter" method="GET"><input name="q" value="{{ request('q') }}" placeholder="Search employee, mobile, department..."><select name="department"><option value="">All Departments</option>@foreach($departments as $d)<option value="{{ $d }}" @selected(request('department')===$d)>{{ $d }}</option>@endforeach</select><select name="status"><option value="">All Status</option>@foreach(['active','on_leave','inactive','terminated'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><button class="hr-btn">Filter</button><a class="hr-btn" href="{{ route('admin.staff.index') }}">Reset</a></form>
<div class="hr-card"><div class="hr-table-wrap"><table class="hr-table"><thead><tr><th>Employee</th><th>Code</th><th>Department</th><th>Designation</th><th>Joining</th><th>Status</th><th></th></tr></thead><tbody>@forelse($staff as $person)<tr><td><strong>{{ $person->full_name }}</strong><small>{{ $person->mobile ?: $person->email }}</small></td><td>{{ $person->employee_code }}</td><td>{{ $person->department ?: '—' }}</td><td>{{ $person->designation ?: '—' }}</td><td>{{ optional($person->joining_date)->format('d M Y') }}</td><td><span class="hr-badge hr-{{ $person->status }}">{{ ucwords(str_replace('_',' ',$person->status)) }}</span></td><td class="hr-actions"><a href="{{ route('admin.staff.show',$person) }}">View</a><a href="{{ route('admin.staff.edit',$person) }}">Edit</a><a href="{{ route('admin.staff.attendance.history',$person) }}">Attendance</a></td></tr>@empty<tr><td colspan="7" class="hr-empty">No staff records found.</td></tr>@endforelse</tbody></table></div><div class="hr-pagination">{{ $staff->links() }}</div></div>
@endsection
