@extends('layouts.admin')
@section('title','Batch '.$batch->batch_number)
@section('page_title','Batch')
@section('breadcrumb','Batches / '.$batch->batch_number)
@push('styles')<link rel="stylesheet" href="{{ asset('css/batch.css') }}">@endpush
@push('scripts')<script src="{{ asset('js/batch.js') }}"></script>@endpush
@section('content')
<div class="bt-shell">
<div class="bt-head"><div><div class="bt-kicker">TRACEABLE PRODUCTION LOT</div><h1>{{ $batch->batch_number }}</h1><p>{{ $batch->product?->name ?? 'Product' }} · {{ $batch->customer?->business_name ?? 'General Stock' }}</p></div><div class="bt-actions"><a class="bt-btn" href="{{ route('admin.batches.index') }}">← Batches</a>@if(!in_array($batch->status,['allocated','exhausted','cancelled']))<a class="bt-btn" href="{{ route('admin.batches.edit',$batch) }}">Edit</a>@endif @if($batch->quality_status==='passed' && !in_array($batch->status,['released','allocated','exhausted']))<form method="POST" action="{{ route('admin.batches.release',$batch) }}">@csrf<button class="bt-btn bt-primary">Release</button></form>@endif @if(!in_array($batch->status,['blocked','exhausted','cancelled']) && !$batch->allocations->count())<form method="POST" action="{{ route('admin.batches.block',$batch) }}" class="bt-inline-form bt-block-form">@csrf<input name="reason" placeholder="Block reason" required><button class="bt-btn bt-danger">Block</button></form>@endif</div></div>
<div class="bt-overview"><div class="bt-card"><span>Status</span><strong class="bt-status {{ $batch->status }}">{{ ucwords(str_replace('_',' ',$batch->status)) }}</strong><small>Quality: {{ ucfirst($batch->quality_status) }}</small></div><div class="bt-card"><span>Produced</span><strong>{{ rtrim(rtrim(number_format($batch->produced_quantity,3),'0'),'.') }}</strong><small>Accepted output</small></div><div class="bt-card"><span>Allocated</span><strong>{{ rtrim(rtrim(number_format($batch->allocatedQuantity(),3),'0'),'.') }}</strong><small>Issued to customers</small></div><div class="bt-card"><span>Available</span><strong>{{ rtrim(rtrim(number_format($batch->calculatedAvailableQuantity(),3),'0'),'.') }}</strong><small>Remaining quantity</small></div></div>
<div class="bt-two"><div class="bt-card"><div class="bt-card-head"><div><div class="bt-kicker">SOURCE</div><h2>Production Trace</h2></div></div><dl class="bt-meta"><div><dt>Production</dt><dd><a href="{{ route('admin.production.show',$batch->productionOrder) }}">{{ $batch->productionOrder?->production_number }}</a></dd></div><div><dt>Customer</dt><dd>{{ $batch->customer?->business_name ?? 'General Stock' }}</dd></div><div><dt>Product</dt><dd>{{ $batch->product?->name }} · {{ $batch->product?->sku }}</dd></div><div><dt>Design</dt><dd>{{ $batch->design?->design_code ?? '—' }}</dd></div><div><dt>Manufacturing</dt><dd>{{ $batch->manufacturing_date?->format('d M Y') }}</dd></div><div><dt>Expiry</dt><dd>{{ $batch->expiry_date?->format('d M Y') ?? '—' }}</dd></div></dl></div>
<div class="bt-card"><div class="bt-card-head"><div><div class="bt-kicker">QUALITY</div><h2>{{ ucfirst($batch->quality_status) }}</h2></div></div><p>{{ $batch->quality_notes ?: 'No quality notes added.' }}</p><p class="bt-muted">Released {{ $batch->released_at?->format('d M Y, h:i A') ?? 'Not released' }} @if($batch->releaser)by {{ $batch->releaser->name }}@endif</p></div></div>
<div class="bt-card"><div class="bt-card-head"><div><div class="bt-kicker">CUSTOMER TRACEABILITY</div><h2>Allocations / Issue History</h2><p>Every allocation is retained so Batch → Customer and Customer → Batch tracing is possible.</p></div></div>
@if($batch->allocations->count())<div class="bt-table-wrap"><table><thead><tr><th>Customer</th><th>Order</th><th>Delivery</th><th>Quantity</th><th>Allocated</th><th>By</th></tr></thead><tbody>@foreach($batch->allocations as $allocation)<tr><td><strong>{{ $allocation->customer?->business_name }}</strong><small>{{ $allocation->customer?->customer_code }}</small></td><td>{{ $allocation->order?->order_number ?? '—' }}</td><td>{{ $allocation->delivery?->delivery_number ?? 'Pending delivery' }}</td><td>{{ rtrim(rtrim(number_format($allocation->quantity,3),'0'),'.') }}</td><td>{{ $allocation->allocated_at?->format('d M Y, h:i A') }}</td><td>{{ $allocation->allocator?->name ?? '—' }}</td></tr>@endforeach</tbody></table></div>@else<div class="bt-empty bt-small"><p>No allocations yet.</p></div>@endif</div>
@if($batch->canAllocate())<div class="bt-card"><div class="bt-card-head"><div><div class="bt-kicker">ALLOCATE STOCK</div><h2>Issue this batch to a customer</h2><p>Available: <strong>{{ rtrim(rtrim(number_format($batch->calculatedAvailableQuantity(),3),'0'),'.') }}</strong></p></div></div><form method="POST" action="{{ route('admin.batches.allocate',$batch) }}" class="bt-allocate-form">@csrf<div class="bt-source-grid"><label>Customer<select name="customer_id" required><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected($batch->customer_id==$customer->id)>{{ $customer->business_name }} · {{ $customer->customer_code }}</option>@endforeach</select></label><label>Order<select name="order_id"><option value="">No order linked</option>@foreach($orders as $order)<option value="{{ $order->id }}">{{ $order->order_number }} · {{ $order->status }}</option>@endforeach</select></label><label>Quantity<input type="number" name="quantity" min="0.001" max="{{ $batch->calculatedAvailableQuantity() }}" step="0.001" required></label></div><label>Notes<textarea name="notes" rows="3"></textarea></label><button class="bt-btn bt-primary">Record Allocation →</button></form></div>@endif
<div class="bt-card"><div class="bt-card-head"><div><div class="bt-kicker">NOTES</div><h2>Batch Notes</h2></div></div><p>{{ $batch->notes ?: 'No batch notes added.' }}</p></div>
</div>
@endsection
