@extends('layouts.admin')
@section('title','Pricing')
@section('page_title','Pricing')
@section('breadcrumb')Catalog / Pricing@endsection
@section('content')
<div class="product-page-shell">
    <div class="page-header"><div><div class="eyebrow">CATALOG / COMMERCIAL RULES</div><h1 class="page-title">Pricing</h1><div class="page-subtitle">Manage global, bulk, recurring and customer-specific product rates.</div></div><a href="{{ route('admin.products.index') }}" class="btn btn-secondary">← Products</a></div>
    <div class="product-stats pricing-stats"><div class="product-stat-card"><span>Active Rules</span><strong>{{ $stats['active'] }}</strong><small>Currently usable</small><i>✓</i></div><div class="product-stat-card"><span>Standard</span><strong>{{ $stats['standard'] }}</strong><small>Global base pricing</small><i>₹</i></div><div class="product-stat-card"><span>Bulk</span><strong>{{ $stats['bulk'] }}</strong><small>Quantity slabs</small><i>↗</i></div><div class="product-stat-card"><span>Customer Specific</span><strong>{{ $stats['customer'] }}</strong><small>Negotiated rates</small><i>◎</i></div></div>
    <div class="product-toolbar card"><form method="GET" class="product-filter-form"><div class="product-search-wrap"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input name="search" value="{{ request('search') }}" placeholder="Search product, SKU or customer..."></div><select name="pricing_type" class="product-filter-select"><option value="">All Types</option>@foreach(['standard','bulk','recurring','custom'] as $type)<option value="{{ $type }}" @selected(request('pricing_type')===$type)>{{ ucfirst($type) }}</option>@endforeach</select><select name="scope" class="product-filter-select"><option value="">All Scopes</option><option value="global" @selected(request('scope')==='global')>Global</option><option value="customer" @selected(request('scope')==='customer')>Customer Specific</option></select><select name="status" class="product-filter-select"><option value="">All Status</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select><button class="btn btn-secondary">Filter</button></form></div>
    <div class="product-catalog-card card"><div class="product-card-head"><div><div class="eyebrow">PRICE BOOK</div><h3>All Pricing Rules</h3><span>{{ $prices->total() }} rules</span></div></div><div class="product-table-wrap"><table class="product-table pricing-table"><thead><tr><th>Product</th><th>Scope</th><th>Type</th><th>Quantity</th><th>Unit Price</th><th>Validity</th><th>Status</th><th></th></tr></thead><tbody>@forelse($prices as $price)<tr><td><a class="product-name" href="{{ route('admin.products.show',$price->product) }}">{{ $price->product->name }}</a><small>{{ $price->product->sku }}</small></td><td><strong>{{ $price->customer?->business_name ?: 'Global' }}</strong><small>{{ $price->customer ? 'Negotiated customer rate' : 'Base catalog rate' }}</small></td><td><span class="pricing-type-badge type-{{ $price->pricing_type }}">{{ ucfirst($price->pricing_type) }}</span></td><td><strong>{{ $price->min_quantity }}{{ $price->max_quantity ? '–'.$price->max_quantity : '+' }}</strong><small>{{ $price->product->unit }}</small></td><td><strong class="pricing-amount">₹{{ number_format((float)$price->unit_price,2) }}</strong><small>per {{ $price->product->unit }}</small></td><td><small>{{ $price->effective_from?->format('d M Y') ?: 'No start' }} → {{ $price->effective_to?->format('d M Y') ?: 'Open ended' }}</small></td><td><span class="product-status {{ $price->status==='active'?'is-active':'is-inactive' }}"><b></b>{{ ucfirst($price->status) }}</span></td><td><a class="product-view-btn" href="{{ route('admin.products.show',$price->product) }}">Open →</a></td></tr>@empty<tr><td colspan="8"><div class="product-empty"><div class="product-empty-icon">₹</div><strong>No pricing rules found</strong><span>Open a product and add its global or customer-specific pricing.</span></div></td></tr>@endforelse</tbody></table></div>@if($prices->hasPages())<div class="product-pagination">{{ $prices->links() }}</div>@endif</div>
</div>
@endsection
