@extends('layouts.admin')
@section('title','Inventory — JALVAN ERP')
@section('page_title','Inventory')
@section('breadcrumb','Catalog / Inventory')
@push('styles')<link rel="stylesheet" href="{{ asset('css/inventory.css') }}">@endpush
@push('scripts')<script src="{{ asset('js/inventory.js') }}"></script>@endpush
@section('content')
<div class="inv-shell">
 <div class="inv-head"><div><div class="inv-kicker">STOCK CONTROL</div><h1>Inventory</h1><p>Track finished goods, materials, stock movements and availability.</p></div><a class="inv-btn inv-primary" href="{{ route('admin.inventory.create') }}">+ New Inventory Item</a></div>
 <div class="inv-stats"><div><span>Active SKUs</span><strong>{{ $stats['skus'] }}</strong><small>Tracked items</small></div><div><span>Low Stock</span><strong>{{ $stats['low_stock'] }}</strong><small>Reorder attention</small></div><div><span>Out of Stock</span><strong>{{ $stats['out_of_stock'] }}</strong><small>Zero on hand</small></div><div><span>Units On Hand</span><strong>{{ rtrim(rtrim(number_format((float)$stats['units'],3),'0'),'.') }}</strong><small>Total stock</small></div><div><span>Reserved</span><strong>{{ rtrim(rtrim(number_format((float)$stats['reserved'],3),'0'),'.') }}</strong><small>Unavailable stock</small></div></div>
 <form class="inv-filters" method="GET"><input name="q" value="{{ request('q') }}" placeholder="Search item, SKU or product…"><select name="category"><option value="">All Categories</option>@foreach(['finished_goods'=>'Finished Goods','raw_material'=>'Raw Material','packaging'=>'Packaging','label'=>'Labels','consumable'=>'Consumables','other'=>'Other'] as $v=>$l)<option value="{{ $v }}" @selected(request('category')===$v)>{{ $l }}</option>@endforeach</select><select name="status"><option value="">All Status</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select><label><input type="checkbox" name="low_stock" value="1" @checked(request()->boolean('low_stock'))> Low stock</label><button class="inv-btn inv-dark">Search</button><a class="inv-btn" href="{{ route('admin.inventory.index') }}">Reset</a></form>
 <div class="inv-card"><div class="inv-card-head"><div><div class="inv-kicker">STOCK LEDGER</div><h2>All Inventory</h2></div><span>{{ $items->total() }} records</span></div><div class="inv-table-wrap"><table><thead><tr><th>Item</th><th>SKU</th><th>Category</th><th>Location</th><th>On Hand</th><th>Reserved</th><th>Available</th><th>Reorder</th><th>Status</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><a href="{{ route('admin.inventory.show',$item) }}"><strong>{{ $item->name }}</strong></a>@if($item->product)<small>{{ $item->product->name }}</small>@endif</td><td>{{ $item->sku }}</td><td>{{ ucwords(str_replace('_',' ',$item->category)) }}</td><td>{{ $item->location ?: '—' }}</td><td>{{ rtrim(rtrim(number_format((float)$item->on_hand,3),'0'),'.') }} {{ $item->unit }}</td><td>{{ rtrim(rtrim(number_format((float)$item->reserved,3),'0'),'.') }}</td><td><strong>{{ rtrim(rtrim(number_format($item->availableQuantity(),3),'0'),'.') }}</strong></td><td>@if($item->reorder_level>0 && $item->on_hand <= $item->reorder_level)<span class="inv-badge warn">Reorder</span>@else<span class="inv-badge ok">OK</span>@endif</td><td><span class="inv-badge {{ $item->status==='active'?'ok':'muted' }}">{{ ucfirst($item->status) }}</span></td><td><a class="inv-link" href="{{ route('admin.inventory.show',$item) }}">View →</a></td></tr>@empty<tr><td colspan="10"><div class="inv-empty"><strong>No inventory items yet</strong><p>Create your first SKU or receive stock from production.</p><a class="inv-btn inv-primary" href="{{ route('admin.inventory.create') }}">+ New Inventory Item</a></div></td></tr>@endforelse</tbody></table></div><div class="inv-pagination">{{ $items->links() }}</div></div>
</div>
@endsection
