@extends('layouts.admin')
@section('title','Inventory — '.$item->name)
@section('page_title','Inventory')
@section('breadcrumb','Catalog / Inventory / '.$item->sku)
@push('styles')<link rel="stylesheet" href="{{ asset('css/inventory.css') }}">@endpush
@section('content')<div class="inv-shell"><div class="inv-head"><div><div class="inv-kicker">INVENTORY ITEM · {{ $item->sku }}</div><h1>{{ $item->name }}</h1><p>{{ $item->product?->name ?? 'Manual inventory item' }} · {{ ucwords(str_replace('_',' ',$item->category)) }}</p></div><div class="inv-actions"><a class="inv-btn" href="{{ route('admin.inventory.index') }}">← Inventory</a><a class="inv-btn inv-primary" href="{{ route('admin.inventory.edit',$item) }}">Edit</a></div></div>
<div class="inv-stats"><div><span>On Hand</span><strong>{{ rtrim(rtrim(number_format((float)$item->on_hand,3),'0'),'.') }}</strong><small>{{ $item->unit }}</small></div><div><span>Reserved</span><strong>{{ rtrim(rtrim(number_format((float)$item->reserved,3),'0'),'.') }}</strong><small>Unavailable</small></div><div><span>Available</span><strong>{{ rtrim(rtrim(number_format($item->availableQuantity(),3),'0'),'.') }}</strong><small>Can issue</small></div><div><span>Average Cost</span><strong>₹{{ number_format((float)$item->average_cost,2) }}</strong><small>Per {{ $item->unit }}</small></div><div><span>Reorder</span><strong>{{ rtrim(rtrim(number_format((float)$item->reorder_level,3),'0'),'.') }}</strong><small>{{ $item->location ?: 'No location' }}</small></div></div>
<div class="inv-two"><div class="inv-card"><div class="inv-card-head"><div><div class="inv-kicker">STOCK MOVEMENT</div><h2>Receive / Issue / Adjust</h2></div></div><div class="inv-movement-forms"><form method="POST" action="{{ route('admin.inventory.receive',$item) }}">@csrf<h3>Receive</h3><input name="quantity" type="number" step="0.001" min="0.001" placeholder="Quantity" required><input name="unit_cost" type="number" step="0.01" min="0" placeholder="Unit cost"><input name="notes" placeholder="Notes"><button class="inv-btn inv-primary">Receive Stock</button></form><form method="POST" action="{{ route('admin.inventory.issue',$item) }}">@csrf<h3>Issue</h3><input name="quantity" type="number" step="0.001" min="0.001" max="{{ $item->availableQuantity() }}" placeholder="Quantity" required><input name="notes" placeholder="Reason / reference"><button class="inv-btn inv-dark">Issue Stock</button></form><form method="POST" action="{{ route('admin.inventory.adjust',$item) }}">@csrf<h3>Adjustment</h3><input name="delta" type="number" step="0.001" placeholder="+ / - quantity" required><input name="notes" placeholder="Reason required" required><button class="inv-btn">Adjust</button></form></div></div><div class="inv-card"><div class="inv-card-head"><div><div class="inv-kicker">RESERVATION</div><h2>Reserve Available Stock</h2></div></div><form method="POST" action="{{ route('admin.inventory.reserve',$item) }}" class="inv-inline-form">@csrf<input name="quantity" type="number" step="0.001" min="0.001" max="{{ $item->availableQuantity() }}" placeholder="Quantity" required><input name="reference_type" placeholder="Reference type"><input name="reference_id" type="number" min="1" placeholder="Reference ID"><button class="inv-btn inv-primary">Reserve</button></form><form method="POST" action="{{ route('admin.inventory.releaseReservation',$item) }}" class="inv-inline-form">@csrf<input name="quantity" type="number" step="0.001" min="0.001" max="{{ $item->reserved }}" placeholder="Quantity" required><input name="reference_type" placeholder="Reference type"><input name="reference_id" type="number" min="1" placeholder="Reference ID"><button class="inv-btn">Release Reservation</button></form></div></div>
<div class="inv-card"><div class="inv-card-head"><div><div class="inv-kicker">LEDGER</div><h2>Recent Movements</h2></div><span>{{ $item->movements->count() }} shown</span></div><div class="inv-table-wrap"><table><thead><tr><th>Date</th><th>Movement</th><th>Quantity</th><th>Batch</th><th>Reference</th><th>By</th><th>Notes</th></tr></thead><tbody>@forelse($item->movements as $m)<tr><td>{{ $m->movement_date?->format('d M Y, h:i A') }}</td><td><span class="inv-badge {{ in_array($m->movement_type,['receipt','opening','production_in','release_reservation','adjustment_in'])?'ok':'warn' }}">{{ ucwords(str_replace('_',' ',$m->movement_type)) }}</span></td><td>{{ rtrim(rtrim(number_format((float)$m->quantity,3),'0'),'.') }}</td><td>{{ $m->batch?->batch_number ?? '—' }}</td><td>{{ $m->reference_type ? $m->reference_type.($m->reference_id?' #'.$m->reference_id:'') : '—' }}</td><td>{{ $m->performer?->name ?? 'System' }}</td><td>{{ $m->notes ?: '—' }}</td></tr>@empty<tr><td colspan="7" class="inv-muted">No stock movements yet.</td></tr>@endforelse</tbody></table></div></div>
</div>@endsection
