@extends('layouts.admin')
@section('title','Complaints / Issues')
@section('page_title','Complaints / Issues')
@section('content')
<link rel="stylesheet" href="{{ asset('css/issues.css') }}">
<div class="issue-page">
    <div class="issue-head"><div><h1>Complaints & Issues</h1><p>Track customer problems, delivery issues, production complaints and internal tasks.</p></div><div class="issue-actions"><a class="issue-btn primary" href="{{ route('admin.issues.create') }}">+ New Issue</a><a class="issue-btn" href="{{ route('admin.issues.categories') }}">Categories</a></div></div>
    <div class="issue-kpis"><div><span>Open</span><strong>{{ $stats['open'] }}</strong></div><div><span>Urgent</span><strong>{{ $stats['urgent'] }}</strong></div><div><span>Overdue</span><strong>{{ $stats['overdue'] }}</strong></div><div><span>Resolved This Month</span><strong>{{ $stats['resolved_month'] }}</strong></div></div>
    <form class="issue-filter" method="GET"><input name="search" value="{{ request('search') }}" placeholder="Search issue, title, customer..."><select name="status"><option value="">All Status</option>@foreach(['open','in_progress','pending_customer','resolved','closed','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><select name="priority"><option value="">All Priority</option>@foreach(['low','normal','high','urgent'] as $p)<option value="{{ $p }}" @selected(request('priority')===$p)>{{ ucfirst($p) }}</option>@endforeach</select><select name="category_id"><option value="">All Categories</option>@foreach($categories as $c)<option value="{{ $c->id }}" @selected(request('category_id')==$c->id)>{{ $c->name }}</option>@endforeach</select><label class="issue-check"><input type="checkbox" name="overdue" value="1" @checked(request('overdue'))> Overdue</label><button class="issue-btn">Filter</button><a class="issue-btn" href="{{ route('admin.issues.index') }}">Reset</a></form>
    <div class="issue-table-wrap"><table class="issue-table"><thead><tr><th>Issue</th><th>Customer</th><th>Category</th><th>Priority</th><th>Status</th><th>Assigned</th><th>Due</th><th>Actions</th></tr></thead><tbody>@forelse($issues as $issue)<tr><td><a href="{{ route('admin.issues.show',$issue) }}"><b>{{ $issue->issue_number }}</b></a><small>{{ $issue->title }}</small></td><td>{{ $issue->customer?->business_name ?? '—' }}</td><td>{{ $issue->category?->name ?? '—' }}</td><td><span class="badge priority-{{ $issue->priority }}">{{ ucfirst($issue->priority) }}</span></td><td><span class="badge status-{{ $issue->status }}">{{ ucwords(str_replace('_',' ',$issue->status)) }}</span></td><td>{{ $issue->assignee?->full_name ?? 'Unassigned' }}</td><td class="{{ $issue->is_overdue ? 'overdue' : '' }}">{{ $issue->due_date?->format('d M Y') ?? '—' }}</td><td><a href="{{ route('admin.issues.show',$issue) }}">View</a> · <a href="{{ route('admin.issues.edit',$issue) }}">Edit</a></td></tr>@empty<tr><td colspan="8" class="empty">No issues found.</td></tr>@endforelse</tbody></table></div>
    <div class="issue-pagination">{{ $issues->links() }}</div>
</div>
@endsection
