@extends('layouts.admin')
@section('title',$issue->issue_number)
@section('page_title','Issue Detail')
@section('content')
<link rel="stylesheet" href="{{ asset('css/issues.css') }}">
<div class="issue-page">
<div class="issue-head"><div><div class="eyebrow">{{ $issue->issue_number }}</div><h1>{{ $issue->title }}</h1><p>{{ $issue->customer?->business_name ?? 'Internal / Unlinked Issue' }}</p></div><div class="issue-actions"><a class="issue-btn" href="{{ route('admin.issues.edit',$issue) }}">Edit</a><form method="POST" action="{{ route('admin.issues.destroy',$issue) }}" onsubmit="return confirm('Archive this issue?')">@csrf @method('DELETE')<button class="issue-btn danger">Archive</button></form></div></div>
<div class="issue-detail-grid"><div class="issue-card"><h3>Overview</h3><div class="detail-row"><span>Status</span><strong class="badge status-{{ $issue->status }}">{{ ucwords(str_replace('_',' ',$issue->status)) }}</strong></div><div class="detail-row"><span>Priority</span><strong class="badge priority-{{ $issue->priority }}">{{ ucfirst($issue->priority) }}</strong></div><div class="detail-row"><span>Category</span><strong>{{ $issue->category?->name ?? '—' }}</strong></div><div class="detail-row"><span>Assigned</span><strong>{{ $issue->assignee?->full_name ?? 'Unassigned' }}</strong></div><div class="detail-row"><span>Due</span><strong class="{{ $issue->is_overdue ? 'overdue' : '' }}">{{ $issue->due_date?->format('d M Y') ?? '—' }}</strong></div><div class="detail-row"><span>Source</span><strong>{{ $issue->source ?: '—' }}</strong></div></div>
<div class="issue-card"><h3>Linked Records</h3><div class="detail-row"><span>Customer</span><strong>{{ $issue->customer?->business_name ?? '—' }}</strong></div><div class="detail-row"><span>Order</span><strong>{{ $issue->order?->order_number ?? ($issue->order_id ? '#'.$issue->order_id : '—') }}</strong></div><div class="detail-row"><span>Delivery</span><strong>{{ $issue->delivery?->delivery_number ?? ($issue->delivery_id ? '#'.$issue->delivery_id : '—') }}</strong></div><div class="detail-row"><span>Batch</span><strong>{{ $issue->batch?->batch_number ?? ($issue->batch_id ? '#'.$issue->batch_id : '—') }}</strong></div></div></div>
<div class="issue-card"><h3>Description</h3><div class="issue-rich">{!! nl2br(e($issue->description)) !!}</div>@if($issue->resolution)<hr><h3>Resolution</h3><div class="issue-rich">{!! nl2br(e($issue->resolution)) !!}</div>@endif</div>
<div class="issue-card"><h3>Update Status</h3><form method="POST" action="{{ route('admin.issues.status',$issue) }}" class="inline-form">@csrf<select name="status">@foreach(['open','in_progress','pending_customer','resolved','closed','cancelled'] as $s)<option value="{{ $s }}" @selected($issue->status===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><input name="message" placeholder="Optional update note"><button class="issue-btn primary">Update Status</button></form></div>
<div class="issue-card"><h3>Assignment</h3><form method="POST" action="{{ route('admin.issues.assign',$issue) }}" class="inline-form">@csrf<select name="assigned_to"><option value="">Unassigned</option>@foreach($staff as $s)<option value="{{ $s->id }}" @selected($issue->assigned_to==$s->id)>{{ $s->full_name }}</option>@endforeach</select><button class="issue-btn primary">Save Assignment</button></form></div>
<div class="issue-card"><h3>Comments & Updates</h3><div class="timeline">@forelse($issue->comments as $comment)<div class="timeline-item"><strong>{{ $comment->user?->name ?? 'User' }}</strong><span>{{ $comment->created_at->format('d M Y h:i A') }}</span><p>{{ $comment->comment }}</p><small>{{ $comment->is_internal ? 'Internal note' : 'Customer visible' }}</small></div>@empty<p class="muted">No comments yet.</p>@endforelse</div><form method="POST" action="{{ route('admin.issues.comments.store',$issue) }}" enctype="multipart/form-data" class="comment-form">@csrf<textarea name="comment" rows="4" required placeholder="Add an update or internal note..."></textarea><label><input type="checkbox" name="is_internal" value="1" checked> Internal note</label><input type="file" name="attachments[]" multiple><button class="issue-btn primary">Add Comment</button></form></div>
<div class="issue-card"><h3>Activity Timeline</h3><div class="timeline">@forelse($issue->activities as $activity)<div class="timeline-item"><strong>{{ $activity->user?->name ?? 'System' }}</strong><span>{{ $activity->created_at->format('d M Y h:i A') }}</span><p>{{ $activity->message }}</p></div>@empty<p class="muted">No activity.</p>@endforelse</div></div>
</div>
@endsection
