@extends('layouts.admin')
@section('title','Production — JALVAN ERP')
@section('page_title','Production')
@section('breadcrumb','Production / Manufacturing')
@push('styles')<link rel="stylesheet" href="{{ asset('css/production.css') }}">@endpush
@push('scripts')<script src="{{ asset('js/production.js') }}"></script>@endpush
@section('content')
<div class="prd-shell"><div class="prd-head"><div><div class="prd-kicker">MANUFACTURING CONTROL</div><h1>Production</h1><p>Turn confirmed orders into controlled production jobs.</p></div><a class="prd-btn prd-primary" href="{{ route('admin.production.create') }}">+ Start Production</a></div>
<div class="prd-stats"><div><span>Total Jobs</span><b>{{ $stats['total'] }}</b></div><div><span>Pending</span><b>{{ $stats['pending'] }}</b></div><div><span>In Production</span><b>{{ $stats['in_progress'] }}</b></div><div><span>Quality Check</span><b>{{ $stats['quality'] }}</b></div><div><span>Completed</span><b>{{ $stats['completed'] }}</b></div><div><span>On Hold</span><b>{{ $stats['on_hold'] }}</b></div></div>
<form class="prd-filters" method="GET"><input name="q" value="{{ request('q') }}" placeholder="Search production, order, customer..."><select name="status"><option value="">All Status</option>@foreach(['pending','scheduled','in_progress','quality_check','on_hold','completed','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><select name="priority"><option value="">All Priority</option>@foreach(['low','normal','high','urgent'] as $s)<option value="{{ $s }}" @selected(request('priority')===$s)>{{ ucfirst($s) }}</option>@endforeach</select><input type="date" name="date" value="{{ request('date') }}"><button class="prd-btn">Search</button><a class="prd-btn" href="{{ route('admin.production.index') }}">Reset</a></form>
<div class="prd-card"><div class="prd-card-head"><div><div class="prd-kicker">PRODUCTION QUEUE</div><h2>All Production Jobs</h2></div><span>{{ $productions->total() }} records</span></div>@if($productions->count())<div class="prd-table-wrap"><table><thead><tr><th>Production</th><th>Order</th><th>Customer</th><th>Planned</th><th>Progress</th><th>Priority</th><th>Status</th><th>Scheduled</th><th></th></tr></thead><tbody>@foreach($productions as $p)<tr><td><strong>{{ $p->production_number }}</strong></td><td>{{ $p->order->order_number }}</td><td>{{ $p->customer->business_name }}</td><td>{{ rtrim(rtrim(number_format($p->planned_quantity,3), '0'),'.') }}</td><td><div class="prd-progress"><i style="width:{{ $p->progress() }}%"></i></div><small>{{ $p->progress() }}%</small></td><td><span class="prd-priority {{ $p->priority }}">{{ ucfirst($p->priority) }}</span></td><td><span class="prd-status {{ $p->status }}">{{ ucwords(str_replace('_',' ',$p->status)) }}</span></td><td>{{ $p->scheduled_date?->format('d M Y') ?? '—' }}</td><td><a class="prd-link" href="{{ route('admin.production.show',$p) }}">View →</a></td></tr>@endforeach</tbody></table></div><div class="prd-pagination">{{ $productions->links() }}</div>@else<div class="prd-empty"><h3>No production jobs yet</h3><p>Confirm an order and start production to create your first manufacturing job.</p><a class="prd-btn prd-primary" href="{{ route('admin.production.create') }}">Start Production</a></div>@endif</div></div>
@endsection
