@extends('layouts.admin')
@section('title','Production '.$p->production_number)
@section('page_title','Production')
@section('breadcrumb','Production / '.$p->production_number)
@push('styles')<link rel="stylesheet" href="{{ asset('css/production.css') }}">@endpush
@section('content')<div class="prd-shell"><div class="prd-head"><div><div class="prd-kicker">MANUFACTURING JOB</div><h1>{{ $p->production_number }}</h1><p>{{ $p->customer->business_name }} · Order {{ $p->order->order_number }}</p></div><div class="prd-actions"><a class="prd-btn" href="{{ route('admin.production.index') }}">← Production</a><a class="prd-btn" href="{{ route('admin.production.edit',$p) }}">Edit</a>@if($p->status==='completed')<a class="prd-btn prd-primary" href="{{ route('admin.batches.create',['production'=>$p->id]) }}">Create Batch →</a>@endif@if(in_array($p->status,['pending','scheduled','on_hold']))<form method="POST" action="{{ route('admin.production.start',$p) }}">@csrf<button class="prd-btn prd-primary">Start Production</button></form>@endif @if(!in_array($p->status,['completed','cancelled']))<form method="POST" action="{{ route('admin.production.cancel',$p) }}" onsubmit="return confirm('Cancel this production job?')">@csrf<button class="prd-btn prd-danger">Cancel</button></form>@endif</div></div>
<div class="prd-overview"><div class="prd-card"><span>Status</span><strong class="prd-status {{ $p->status }}">{{ ucwords(str_replace('_',' ',$p->status)) }}</strong><small>Priority: {{ ucfirst($p->priority) }}</small></div><div class="prd-card"><span>Planned</span><strong>{{ rtrim(rtrim(number_format($p->planned_quantity,3),'0'),'.') }}</strong><small>units</small></div><div class="prd-card"><span>Produced</span><strong>{{ rtrim(rtrim(number_format($p->produced_quantity,3),'0'),'.') }}</strong><small>Accepted output</small></div><div class="prd-card"><span>Progress</span><strong>{{ $p->progress() }}%</strong><div class="prd-progress"><i style="width:{{ $p->progress() }}%"></i></div></div></div>
<div class="prd-two"><div class="prd-card"><div class="prd-card-head"><div><div class="prd-kicker">OUTPUT CONTROL</div><h2>Production Quantity</h2></div></div><form method="POST" action="{{ route('admin.production.progress',$p) }}" class="prd-grid">@csrf<label>Produced / Accepted<input type="number" step="0.001" min="0" max="{{ $p->planned_quantity }}" name="produced_quantity" value="{{ $p->produced_quantity }}"></label><label>Rejected<input type="number" step="0.001" min="0" name="rejected_quantity" value="{{ $p->rejected_quantity }}"></label><label>Waste<input type="number" step="0.001" min="0" name="waste_quantity" value="{{ $p->waste_quantity }}"></label><div><button class="prd-btn prd-primary">Update Output</button></div></form></div><div class="prd-card"><div class="prd-card-head"><div><div class="prd-kicker">QUALITY</div><h2>{{ ucfirst($p->quality_status) }}</h2></div></div><p>{{ $p->quality_notes ?: 'No quality notes added.' }}</p></div></div>
<div class="prd-card"><div class="prd-card-head"><div><div class="prd-kicker">PRODUCTION FLOW</div><h2>Manufacturing Steps</h2></div></div><div class="prd-steps">@foreach($p->steps as $step)<div class="prd-step"><div class="prd-step-dot {{ $step->status }}"></div><div><strong>{{ $step->name }}</strong><small>{{ ucwords(str_replace('_',' ',$step->status)) }}</small></div><form method="POST" action="{{ route('admin.production.step',[$p,$step]) }}">@csrf<select name="status" onchange="this.form.submit()"><option value="pending" @selected($step->status==='pending')>Pending</option><option value="in_progress" @selected($step->status==='in_progress')>In Progress</option><option value="completed" @selected($step->status==='completed')>Completed</option><option value="skipped" @selected($step->status==='skipped')>Skipped</option></select></form></div>@endforeach</div></div>
<div class="prd-card"><div class="prd-card-head"><div><div class="prd-kicker">ORDER ITEMS</div><h2>Production Plan</h2></div></div><div class="prd-table-wrap"><table><thead><tr><th>Product</th><th>Description</th><th>Planned</th><th>Produced</th><th>Rejected</th></tr></thead><tbody>@foreach($p->items as $i)<tr><td>{{ $i->product?->name ?? '—' }}</td><td>{{ $i->description }}</td><td>{{ $i->planned_quantity }} {{ $i->unit }}</td><td>{{ $i->produced_quantity }}</td><td>{{ $i->rejected_quantity }}</td></tr>@endforeach</tbody></table></div></div>
<div class="prd-two"><div class="prd-card"><div class="prd-kicker">DESIGN</div><h2>{{ $p->design?->title ?? 'No design linked' }}</h2><p>{{ $p->design?->design_code ?? '—' }}</p></div><div class="prd-card"><div class="prd-kicker">SCHEDULING</div><p><strong>Scheduled:</strong> {{ $p->scheduled_date?->format('d M Y') ?? 'Not scheduled' }}</p><p><strong>Assigned:</strong> {{ $p->assignee?->name ?? 'Unassigned' }}</p><p><strong>Started:</strong> {{ $p->started_at?->format('d M Y, h:i A') ?? '—' }}</p></div></div>
@if($p->status==='quality_check')<form method="POST" action="{{ route('admin.production.status',$p) }}" class="prd-complete-form">@csrf<input type="hidden" name="status" value="completed"><button class="prd-btn prd-primary" onclick="return confirm('Complete production after quality check?')">Complete Production →</button></form>@endif
</div>@endsection
