@php($editing = isset($payment))
<div class="pm-grid">
 <section class="pm-card"><h3>Payment Type</h3><div class="pm-field"><label>Direction</label><select name="direction" id="pm-direction" required><option value="received" @selected(old('direction',$payment->direction??'received')==='received')>Received — Customer → JALVAN</option><option value="paid" @selected(old('direction',$payment->direction??'')==='paid')>Paid — JALVAN → Supplier</option></select></div>
 <div class="pm-field"><label>Payment Type</label><select name="payment_type"><option value="customer_payment">Customer Payment</option><option value="supplier_payment">Supplier Payment</option><option value="advance">Advance</option><option value="invoice_payment">Invoice Payment</option><option value="purchase_payment">Purchase Payment</option><option value="order_payment">Order Payment</option><option value="adjustment">Adjustment</option></select></div>
 <div class="pm-field" id="pm-customer"><label>Customer</label><select name="customer_id"><option value="">Select customer</option>@foreach($customers as $c)<option value="{{$c->id}}" @selected(old('customer_id',$payment->customer_id??'')==$c->id)>{{ $c->business_name }}{{ $c->customer_code ? ' — '.$c->customer_code : '' }}</option>@endforeach</select></div>
 <div class="pm-field" id="pm-supplier"><label>Supplier</label><select name="supplier_id"><option value="">Select supplier</option>@foreach($suppliers as $s)<option value="{{$s->id}}" @selected(old('supplier_id',$payment->supplier_id??'')==$s->id)>{{ $s->business_name ?? $s->name ?? ('Supplier #'.$s->id) }}</option>@endforeach</select></div></section>
 <section class="pm-card"><h3>Payment Details</h3><div class="pm-field"><label>Amount</label><input type="number" step="0.01" min="0.01" name="amount" value="{{old('amount',$payment->amount??'')}}" required></div><div class="pm-field"><label>Payment Date</label><input type="date" name="payment_date" value="{{old('payment_date',isset($payment)?$payment->payment_date?->format('Y-m-d'):now()->format('Y-m-d'))}}" required></div><div class="pm-field"><label>Method</label><select name="method" id="pm-method"><option>cash</option><option>upi</option><option>bank_transfer</option><option>card</option><option>cheque</option><option>neft</option><option>rtgs</option><option>imps</option><option>other</option></select></div><div class="pm-field"><label>Reference / UTR</label><input name="reference_number" value="{{old('reference_number',$payment->reference_number??'')}}" maxlength="120"></div><div class="pm-field"><label>Bank Name</label><input name="bank_name" value="{{old('bank_name',$payment->bank_name??'')}}"></div><div class="pm-field"><label>Notes</label><textarea name="notes">{{old('notes',$payment->notes??'')}}</textarea></div></section>
</div>
<div class="pm-card pm-summary"><div><span>Payment</span><strong id="pm-total">₹ 0.00</strong></div><div><span>Allocated</span><strong id="pm-allocated">₹ 0.00</strong></div><div><span>Unallocated / Advance</span><strong id="pm-unallocated">₹ 0.00</strong></div></div>
