@extends('layouts.admin')
@section('title','Design Preview — '.$design->title)
@section('page_title','Design Preview')
@section('breadcrumb') CRM / Design Studio / {{ $design->design_code }} @endsection
@push('styles')    
    <link rel="stylesheet" href="{{ asset('css/design-studio.css') }}">
@endpush
@push('scripts')    
    <script src="{{ asset('js/design-studio.js') }}"></script>
@endpush

@section('content')
@php $data=$version?->design_data ?? []; @endphp
<div class="ds-shell"><div class="ds-page-head"><div><div class="ds-kicker">{{ $design->design_code }} · V{{ $version?->version_no ?? 1 }}</div><h1>{{ $design->title }}</h1><p>{{ $design->customer->business_name }} · {{ $design->product?->name ?? 'Bottle product' }}</p></div><div class="ds-top-actions"><a class="btn btn-secondary" href="{{ route('admin.designs.index') }}">← Designs</a><a class="btn btn-primary" href="{{ route('admin.designs.edit',$design) }}">Edit Studio →</a></div></div>
<div class="ds-preview-grid"><div class="card ds-preview-card"><div class="ds-card-head"><div><div class="ds-kicker">LIVE ARTWORK DATA</div><h3>Front / Back preview</h3></div><span class="ds-status ds-{{ $design->status }}"><b></b>{{ ucwords(str_replace('_',' ',$design->status)) }}</span></div><div class="ds-preview-stage"><div class="ds-preview-bottle"><div class="ds-preview-label" style="background:{{ data_get($data,'front.background','#fff') }};color:{{ data_get($data,'front.accent','#111827') }}"><strong>{{ data_get($data,'front.title','PURE TASTE') }}</strong><span>{{ data_get($data,'front.subtitle','Premium drinking water') }}</span><small>{{ data_get($data,'front.body','CUSTOM BRANDED WATER') }}</small><em>QR</em><footer>{{ data_get($data,'front.footer','PURE • SAFE • PREMIUM') }}</footer></div></div><div class="ds-preview-bottle back"><div class="ds-preview-label" style="background:{{ data_get($data,'back.background','#fff') }};color:{{ data_get($data,'back.accent','#111827') }}"><strong>{{ data_get($data,'back.title','OUR MENU') }}</strong><span>{{ data_get($data,'back.subtitle','Scan to explore') }}</span><small>{{ data_get($data,'back.body','Your brand. Your story. Your bottle.') }}</small><em>QR</em><footer>{{ data_get($data,'back.footer','THANK YOU • VISIT AGAIN') }}</footer></div></div></div></div><aside class="ds-preview-side"><div class="ds-side-card"><span>Customer</span><strong>{{ $design->customer->business_name }}</strong><small>{{ $design->customer->customer_code }}</small></div><div class="ds-side-card"><span>Version</span><strong>V{{ $version?->version_no ?? 1 }}</strong><small>{{ $version?->status }}</small></div><div class="ds-side-card"><span>QR Destination</span><strong class="ds-url">{{ data_get($data,'global.qr_url','Not configured') }}</strong></div><div class="ds-side-card"><span>Brief</span><p>{{ $design->brief ?: 'No brief added.' }}</p></div><div class="ds-side-card"><div class="ds-kicker">VERSION HISTORY</div>@foreach($design->versions->sortByDesc('version_no') as $v)<div class="ds-version-row"><span>V{{ $v->version_no }}</span><b>{{ ucfirst($v->status) }}</b><small>{{ $v->created_at->format('d M Y') }}</small></div>@endforeach</div></aside></div>
@if($version)<div class="card ds-comments"><div class="ds-card-head"><div><div class="ds-kicker">COLLABORATION</div><h3>Comments & review</h3></div></div>@forelse($version->comments as $comment)<div class="ds-comment"><span>{{ strtoupper(substr($comment->user?->name ?? 'A',0,1)) }}</span><div><strong>{{ $comment->user?->name ?? 'Admin' }}</strong><small>{{ $comment->created_at->format('d M Y, h:i A') }} · {{ ucfirst($comment->type) }}</small><p>{{ $comment->comment }}</p></div></div>@empty<p class="ds-muted">No comments on this version yet.</p>@endforelse<form method="POST" action="{{ route('admin.designs.comment',[$design,$version]) }}" class="ds-comment-form">@csrf<textarea name="comment" placeholder="Add a design review comment..." required></textarea><button class="btn btn-secondary">Add Comment</button></form></div>@endif
</div>
@endsection
