<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Http\Requests\{StoreInvoiceRequest,UpdateInvoiceRequest,CancelInvoiceRequest}; use App\Models\{Invoice,Customer,Order}; use App\Services\InvoiceService; use Illuminate\Http\Request;
class InvoiceController extends Controller { public function __construct(private InvoiceService $service){}
 public function index(Request $r){$q=Invoice::with(['customer','order'])->latest();if($s=$r->input('search'))$q->where(fn($x)=>$x->where('invoice_number','like',"%$s%")->orWhereHas('customer',fn($c)=>$c->where('business_name','like',"%$s%"))->orWhereHas('order',fn($o)=>$o->where('order_number','like',"%$s%")));foreach(['status','payment_status','customer_id'] as $f)if($r->filled($f))$q->where($f,$r->input($f));if($r->filled('from'))$q->whereDate('invoice_date','>=',$r->input('from'));if($r->filled('to'))$q->whereDate('invoice_date','<=',$r->input('to'));$invoices=$q->paginate(20)->withQueryString();$month=now()->startOfMonth();$stats=['invoiced'=>Invoice::where('invoice_date','>=',$month)->where('status','!=','cancelled')->sum('grand_total'),'paid'=>Invoice::where('invoice_date','>=',$month)->sum('paid_amount'),'outstanding'=>Invoice::where('status','!=','cancelled')->sum('outstanding_amount'),'overdue'=>Invoice::where('status','!=','cancelled')->where('outstanding_amount','>',0)->whereDate('due_date','<',today())->sum('outstanding_amount'),'draft'=>Invoice::where('status','draft')->count(),'partial'=>Invoice::where('payment_status','partially_paid')->count(),'paid_count'=>Invoice::where('payment_status','paid')->count(),'cancelled'=>Invoice::where('status','cancelled')->count()];return view('admin.invoices.index',compact('invoices','stats'));}
 public function create(Request $r){$customers=Customer::orderBy('business_name')->get();$order=$r->filled('order_id')?Order::with('items.product')->findOrFail($r->order_id):null;return view('admin.invoices.create',compact('customers','order'));} public function createFromOrder(Order $order){$customers=Customer::orderBy('business_name')->get();$order->load('items.product','customer');return view('admin.invoices.create',compact('customers','order'));}
 public function store(StoreInvoiceRequest $r){$i=$this->service->createInvoice($r->validated(),auth()->id());return redirect()->route('admin.invoices.show',$i)->with('success','Invoice created.');}
 public function show(Invoice $invoice){$invoice->load(['customer','order','items.product','paymentAllocations.payment']);$invoice=$this->service->syncPaymentStatus($invoice);return view('admin.invoices.show',compact('invoice'));}
 public function edit(Invoice $invoice){$customers=Customer::orderBy('business_name')->get();$invoice->load('items');return view('admin.invoices.edit',compact('invoice','customers'));}
 public function update(UpdateInvoiceRequest $r,Invoice $invoice){$this->service->updateInvoice($invoice,$r->validated(),auth()->id());return redirect()->route('admin.invoices.show',$invoice)->with('success','Invoice updated.');}
 public function issue(Invoice $invoice){$this->service->issue($invoice);return back()->with('success','Invoice issued.');}
 public function cancel(CancelInvoiceRequest $r,Invoice $invoice){$this->service->cancel($invoice,$r->validated('cancellation_reason'),auth()->id());return back()->with('success','Invoice cancelled.');}
 public function duplicate(Invoice $invoice){$n=$this->service->duplicate($invoice,auth()->id());return redirect()->route('admin.invoices.edit',$n)->with('success','Draft invoice duplicated.');}
 public function print(Invoice $invoice){$invoice->load(['customer','order','items.product']);return view('admin.invoices.print',compact('invoice'));}
 public function pdf(Invoice $invoice){$invoice->load(['customer','order','items.product']);if(class_exists('Barryvdh\\DomPDF\\Facade\\Pdf'))return \Barryvdh\DomPDF\Facade\Pdf::loadView('admin.invoices.print',compact('invoice'))->setPaper('a4')->download($invoice->invoice_number.'.pdf');return redirect()->route('admin.invoices.print',$invoice)->with('warning','PDF package is not installed; use Print to save as PDF.');}
}
