<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Http\Requests\{StorePaymentRequest,UpdatePaymentRequest,AllocatePaymentRequest,RefundPaymentRequest}; use App\Models\{Payment,PaymentAllocation,Customer,Supplier}; use App\Services\PaymentService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Throwable;
class PaymentController extends Controller {
 public function __construct(private PaymentService $service){}
 public function index(Request $r){$filters=$r->only(['search','direction','status','method','payment_type','from','to']); $payments=$this->service->query($filters)->paginate(20)->withQueryString(); $month=now()->startOfMonth(); return view('admin.payments.index',compact('payments','filters','month'));}
 public function create(Request $r){$customers=Customer::orderBy('business_name')->get(); $suppliers=Supplier::orderBy('business_name')->get(); return view('admin.payments.create',compact('customers','suppliers'));}
 public function store(StorePaymentRequest $r){try{$p=$this->service->createPayment($r->validated(),$r->user()->id); return redirect()->route('admin.payments.show',$p)->with('success','Payment created successfully.');}catch(Throwable $e){return back()->withInput()->withErrors(['payment'=>$e->getMessage()]);}}
 public function show(Payment $payment){$payment->load(['customer','supplier','order','purchase','invoice','creator','approver','allocations.invoice','allocations.order','allocations.purchase','refunds']); return view('admin.payments.show',compact('payment'));}
 public function edit(Payment $payment){$this->authorize('update',$payment); $customers=Customer::orderBy('business_name')->get(); $suppliers=Supplier::orderBy('business_name')->get(); return view('admin.payments.edit',compact('payment','customers','suppliers'));}
 public function update(UpdatePaymentRequest $r,Payment $payment){try{$this->authorize('update',$payment); $payment->update(collect($r->validated())->except('allocations')->all()); return redirect()->route('admin.payments.show',$payment)->with('success','Payment updated.');}catch(Throwable $e){return back()->withInput()->withErrors(['payment'=>$e->getMessage()]);}}
 public function cancel(Request $r,Payment $payment){$this->authorize('delete',$payment); try{$this->service->cancelPayment($payment,$r->user()->id); return back()->with('success','Payment cancelled and allocations reversed.');}catch(Throwable $e){return back()->withErrors(['payment'=>$e->getMessage()]);}}
 public function allocate(AllocatePaymentRequest $r,Payment $payment){$this->authorize('allocate',$payment); try{$this->service->allocatePayment($payment,$r->validated()['allocations'],$r->user()->id); return back()->with('success','Allocation saved.');}catch(Throwable $e){return back()->withErrors(['allocation'=>$e->getMessage()]);}}
 public function deallocate(Request $r,PaymentAllocation $allocation){$this->authorize('allocate',$allocation->payment); try{$this->service->removeAllocation($allocation,$r->user()->id,$r->input('reason','Manual reversal')); return back()->with('success','Allocation reversed.');}catch(Throwable $e){return back()->withErrors(['allocation'=>$e->getMessage()]);}}
 public function refund(RefundPaymentRequest $r,Payment $payment){$this->authorize('refund',$payment); try{$this->service->refundPayment($payment,$r->validated(),$r->user()->id); return back()->with('success','Refund recorded as a separate transaction.');}catch(Throwable $e){return back()->withErrors(['refund'=>$e->getMessage()]);}}
 public function approve(Request $r,Payment $payment){$this->authorize('approve',$payment); $this->service->approvePayment($payment,$r->user()->id); return back()->with('success','Payment approved.');}
 public function receipt(Payment $payment){$payment->load(['customer','supplier','order','purchase','invoice','creator','allocations.invoice','allocations.order','allocations.purchase']); return view('admin.payments.receipt',compact('payment'));}
 public function pdf(Payment $payment){$payment->load(['customer','supplier','order','purchase','invoice','creator','allocations.invoice','allocations.order','allocations.purchase']); if(class_exists(\Barryvdh\DomPDF\Facade\Pdf::class)){return \Barryvdh\DomPDF\Facade\Pdf::loadView('admin.payments.receipt',compact('payment'))->download($payment->payment_number.'.pdf');} return redirect()->route('admin.payments.receipt',$payment)->with('warning','PDF package is not installed; use Print → Save as PDF.');}
 public function customerLedger(Request $r){$customers=Customer::orderBy('business_name')->get(); $rows=collect(); if($r->filled('customer_id'))$rows=$this->service->getCustomerLedger((int)$r->customer_id,$r->from,$r->to); return view('admin.payments.customer-ledger',compact('customers','rows'));}
 public function supplierLedger(Request $r){$suppliers=Supplier::orderBy('business_name')->get(); $rows=collect(); if($r->filled('supplier_id'))$rows=$this->service->getSupplierLedger((int)$r->supplier_id,$r->from,$r->to); return view('admin.payments.supplier-ledger',compact('suppliers','rows'));}
}
